
package ai.h2o.hive.udf;
/*
  Licensed under the Apache License, Version 2.0
    http://www.apache.org/licenses/LICENSE-2.0.html

  AUTOGENERATED BY H2O at 2016-02-06T02:00:42.294-08:00
  3.6.0.8
  
  Standalone prediction code with sample test data for GBMModel named GBM_Model

  How to download, compile and execute:
      mkdir tmpdir
      cd tmpdir
      curl http://127.0.0.1:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
      curl http://127.0.0.1:54321/3/Models.java/GBM_Model > GBM_Model.java
      javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m GBM_Model.java

     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
*/
import java.util.Map;
import hex.genmodel.GenModel;
import hex.genmodel.annotations.ModelPojo;

@ModelPojo(name="GBM_Model", algorithm="gbm")
public class GBM_Model extends GenModel {
  public hex.ModelCategory getModelCategory() { return hex.ModelCategory.Binomial; }

  public boolean isSupervised() { return true; }
  public int nfeatures() { return 10; }
  public int nclasses() { return 2; }

  // Names of columns used by model.
  public static final String[] NAMES = NamesHolder_GBM_Model.VALUES;
  // Number of output classes included in training data response column.
  public static final int NCLASSES = 2;

  // Column domains. The last array contains domain of response column.
  public static final String[][] DOMAINS = new String[][] {
    /* C1 */ null,
    /* C2 */ null,
    /* C3 */ null,
    /* C4 */ null,
    /* C5 */ null,
    /* C6 */ null,
    /* C7 */ null,
    /* C8 */ null,
    /* C9 */ null,
    /* C10 */ null,
    /* response */ GBM_Model_ColInfo_10.VALUES
  };
  // Prior class distribution
  public static final double[] PRIOR_CLASS_DISTRIB = {0.500666693603782,0.49933330639621804};
  // Class distribution used for model building
  public static final double[] MODEL_CLASS_DISTRIB = {0.500666693603782,0.49933330639621804};

  public GBM_Model() { super(NAMES,DOMAINS); }
  public String getUUID() { return Long.toString(-5942688362272362480L); }

  // Pass in data in a double[], pre-aligned to the Model's requirements.
  // Jam predictions into the preds[] array; preds[0] is reserved for the
  // main prediction (class for classifiers or value for regression),
  // and remaining columns hold a probability distribution for classifiers.
  public final double[] score0( double[] data, double[] preds ) {
    java.util.Arrays.fill(preds,0);
    double[] fdata = hex.genmodel.GenModel.SharedTree_clean(data);
    GBM_Model_Forest_0.score0(fdata,preds);
    GBM_Model_Forest_1.score0(fdata,preds);
    GBM_Model_Forest_2.score0(fdata,preds);
    GBM_Model_Forest_3.score0(fdata,preds);
    GBM_Model_Forest_4.score0(fdata,preds);
    GBM_Model_Forest_5.score0(fdata,preds);
    GBM_Model_Forest_6.score0(fdata,preds);
    GBM_Model_Forest_7.score0(fdata,preds);
    GBM_Model_Forest_8.score0(fdata,preds);
    GBM_Model_Forest_9.score0(fdata,preds);
    GBM_Model_Forest_10.score0(fdata,preds);
    GBM_Model_Forest_11.score0(fdata,preds);
    GBM_Model_Forest_12.score0(fdata,preds);
    GBM_Model_Forest_13.score0(fdata,preds);
    GBM_Model_Forest_14.score0(fdata,preds);
    GBM_Model_Forest_15.score0(fdata,preds);
    GBM_Model_Forest_16.score0(fdata,preds);
    GBM_Model_Forest_17.score0(fdata,preds);
    GBM_Model_Forest_18.score0(fdata,preds);
    GBM_Model_Forest_19.score0(fdata,preds);
    GBM_Model_Forest_20.score0(fdata,preds);
    GBM_Model_Forest_21.score0(fdata,preds);
    GBM_Model_Forest_22.score0(fdata,preds);
    GBM_Model_Forest_23.score0(fdata,preds);
    GBM_Model_Forest_24.score0(fdata,preds);
    GBM_Model_Forest_25.score0(fdata,preds);
    GBM_Model_Forest_26.score0(fdata,preds);
    GBM_Model_Forest_27.score0(fdata,preds);
    GBM_Model_Forest_28.score0(fdata,preds);
    GBM_Model_Forest_29.score0(fdata,preds);
    GBM_Model_Forest_30.score0(fdata,preds);
    GBM_Model_Forest_31.score0(fdata,preds);
    GBM_Model_Forest_32.score0(fdata,preds);
    GBM_Model_Forest_33.score0(fdata,preds);
    GBM_Model_Forest_34.score0(fdata,preds);
    GBM_Model_Forest_35.score0(fdata,preds);
    GBM_Model_Forest_36.score0(fdata,preds);
    GBM_Model_Forest_37.score0(fdata,preds);
    GBM_Model_Forest_38.score0(fdata,preds);
    GBM_Model_Forest_39.score0(fdata,preds);
    GBM_Model_Forest_40.score0(fdata,preds);
    GBM_Model_Forest_41.score0(fdata,preds);
    GBM_Model_Forest_42.score0(fdata,preds);
    GBM_Model_Forest_43.score0(fdata,preds);
    GBM_Model_Forest_44.score0(fdata,preds);
    GBM_Model_Forest_45.score0(fdata,preds);
    GBM_Model_Forest_46.score0(fdata,preds);
    GBM_Model_Forest_47.score0(fdata,preds);
    GBM_Model_Forest_48.score0(fdata,preds);
    GBM_Model_Forest_49.score0(fdata,preds);
    preds[2] = preds[1] + -0.0026667759955681454;
    preds[2] = 1/(1+Math.min(1.0E19, Math.exp(-preds[2])));
    preds[1] = 1.0-preds[2];
    preds[0] = hex.genmodel.GenModel.getPrediction(preds, PRIOR_CLASS_DISTRIB, data, 0.466907139717947);
    return preds;
  }
}
// The class representing training column names
class NamesHolder_GBM_Model implements java.io.Serializable {
  public static final String[] VALUES = new String[10];
  static {
    NamesHolder_GBM_Model_0.fill(VALUES);
  }
  static final class NamesHolder_GBM_Model_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "C1";
      sa[1] = "C2";
      sa[2] = "C3";
      sa[3] = "C4";
      sa[4] = "C5";
      sa[5] = "C6";
      sa[6] = "C7";
      sa[7] = "C8";
      sa[8] = "C9";
      sa[9] = "C10";
    }
  }
}
// The class representing column response
class GBM_Model_ColInfo_10 implements java.io.Serializable {
  public static final String[] VALUES = new String[2];
  static {
    GBM_Model_ColInfo_10_0.fill(VALUES);
  }
  static final class GBM_Model_ColInfo_10_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "0";
      sa[1] = "1";
    }
  }
}

class GBM_Model_Forest_0 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_0_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_0_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[9 /* C10 */] != 74.0f
      ? (data[3 /* C4 */] <55.467194f
        ? (data[4 /* C5 */] <45.31195f
          ? (data[6 /* C7 */] <95.31062f
            ? (data[2 /* C3 */] <60.5f ? -0.0012549652f : 0.004014365f)
            : (data[8 /* C9 */] <37.500908f ? 0.0052328263f : 0.03673083f))
          : (data[1 /* C2 */] <-15.624229f
            ? (data[6 /* C7 */] <-96.85857f ? -0.053733416f : -0.007071933f)
            : (data[6 /* C7 */] <93.7398f ? -6.244979E-4f : -0.026471337f)))
        : (data[1 /* C2 */] <67.96776f
          ? (data[7 /* C8 */] <71.871185f
            ? (data[5 /* C6 */] <-43.742527f ? -0.0030262226f : 0.005433533f)
            : (data[2 /* C3 */] <40.5f ? -0.0022591592f : -0.026291635f))
          : (data[5 /* C6 */] <78.1033f
            ? (data[1 /* C2 */] <97.49583f ? 0.019844713f : -0.017619533f)
            : (data[7 /* C8 */] <78.09051f ? -0.03649351f : 0.07718989f))))
      : (data[6 /* C7 */] <84.17798f
        ? (data[6 /* C7 */] <80.59677f
          ? (data[2 /* C3 */] <-91.0f
            ? (data[1 /* C2 */] <-20.39531f ? 0.04026675f : -0.11084463f)
            : (data[5 /* C6 */] <84.3346f ? 0.04136264f : -0.024733366f))
          : -0.12700628f)
        : (data[6 /* C7 */] <91.72775f
          ? 0.17360032f
          : (data[8 /* C9 */] <8.231258f ? 0.12026689f : 2.666776E-4f))));
    return pred;
  }
}


class GBM_Model_Forest_1 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_1_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_1_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[9 /* C10 */] != 74.0f
      ? (data[3 /* C4 */] <55.467194f
        ? (data[4 /* C5 */] <45.31195f
          ? (data[2 /* C3 */] <68.5f
            ? (data[1 /* C2 */] <96.87338f ? -0.0010564346f : 0.017743895f)
            : (data[7 /* C8 */] <84.36897f ? 0.0060331905f : -0.012464293f))
          : (data[3 /* C4 */] <-97.570045f
            ? (data[6 /* C7 */] <37.497658f ? -0.0035687499f : -0.058807466f)
            : (data[3 /* C4 */] <-30.619217f ? 3.1259298E-4f : -0.0062215165f)))
        : (data[1 /* C2 */] <67.96776f
          ? (data[7 /* C8 */] <93.74533f
            ? (data[4 /* C5 */] <-49.983948f ? -0.0033858677f : 0.0036194148f)
            : (data[2 /* C3 */] <-79.5f ? 0.051340368f : -0.03199351f))
          : (data[5 /* C6 */] <78.1033f
            ? (data[3 /* C4 */] <58.957253f ? 0.04752693f : 0.0122729f)
            : (data[7 /* C8 */] <78.09051f ? -0.032857195f : 0.06957072f))))
      : (data[6 /* C7 */] <84.17798f
        ? (data[6 /* C7 */] <80.59677f
          ? (data[2 /* C3 */] <-91.0f
            ? (data[7 /* C8 */] <-8.995571f ? -0.11296422f : 0.019792523f)
            : (data[8 /* C9 */] <43.601524f ? 0.020822594f : 0.058028255f))
          : -0.11480483f)
        : (data[8 /* C9 */] <41.26139f
          ? (data[3 /* C4 */] <4.23711f ? 0.18853167f : 0.065954305f)
          : 0.027876962f)));
    return pred;
  }
}


class GBM_Model_Forest_2 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_2_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_2_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != -55.0f
      ? (data[9 /* C10 */] <-83.5f
        ? (data[7 /* C8 */] <92.18712f
          ? (data[9 /* C10 */] != -91.0f
            ? (data[5 /* C6 */] <-62.498833f ? -0.015629048f : -0.0019861092f)
            : (data[2 /* C3 */] <-79.5f ? -0.048929833f : 0.025776703f))
          : (data[3 /* C4 */] <87.46052f
            ? (data[9 /* C10 */] <-86.5f ? -0.021668388f : -0.11557658f)
            : 0.11395375f))
        : (data[5 /* C6 */] <-71.87284f
          ? (data[6 /* C7 */] <-81.24924f
            ? (data[5 /* C6 */] <-91.21045f ? -0.004269883f : 0.03226568f)
            : (data[8 /* C9 */] <-78.12308f ? -0.007251524f : 0.004214276f))
          : (data[8 /* C9 */] <96.87463f
            ? (data[3 /* C4 */] <53.123474f ? -8.378058E-4f : 0.0032569068f)
            : (data[5 /* C6 */] <-66.50146f ? -0.1584237f : -0.010354863f))))
      : (data[7 /* C8 */] <-84.96031f
        ? (data[4 /* C5 */] <53.575356f
          ? (data[6 /* C7 */] <11.708824f ? 1.5096851E-4f : -0.13290058f)
          : -0.19820088f)
        : (data[8 /* C9 */] <75.55473f
          ? (data[5 /* C6 */] <-20.425232f
            ? (data[6 /* C7 */] <-52.63139f ? -0.12422852f : -0.024577541f)
            : (data[6 /* C7 */] <-86.855125f ? 0.094849885f : -0.018960176f))
          : (data[1 /* C2 */] <45.750847f
            ? (data[5 /* C6 */] <-23.661362f ? 0.100593075f : -0.051446658f)
            : 0.16839455f))));
    return pred;
  }
}


class GBM_Model_Forest_3 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_3_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_3_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[9 /* C10 */] != 74.0f
      ? (data[2 /* C3 */] <96.5f
        ? (data[3 /* C4 */] <8.592918f
          ? (data[1 /* C2 */] <98.43585f
            ? (data[7 /* C8 */] <53.125114f ? -2.0923413E-4f : -0.0055310023f)
            : (data[8 /* C9 */] <-65.62535f ? -0.03400882f : 0.03971811f))
          : (data[6 /* C7 */] <-98.436455f
            ? (data[1 /* C2 */] <-18.749374f ? -0.043975264f : -0.0021566006f)
            : (data[6 /* C7 */] <-79.833244f ? 0.0094491495f : 0.0012652031f)))
        : (data[1 /* C2 */] <-2.3432617f
          ? (data[8 /* C9 */] <81.23553f
            ? (data[8 /* C9 */] <-91.330536f ? -0.09755492f : -0.020246286f)
            : (data[8 /* C9 */] <83.829315f ? -0.20045309f : -0.05890257f))
          : (data[6 /* C7 */] <18.752281f
            ? (data[6 /* C7 */] <0.22541046f ? 0.015254637f : 0.08279912f)
            : (data[7 /* C8 */] <-37.493893f ? -0.05291274f : 4.6847088E-4f))))
      : (data[6 /* C7 */] <84.17798f
        ? (data[6 /* C7 */] <80.59677f
          ? (data[7 /* C8 */] <-69.548225f
            ? (data[7 /* C8 */] <-96.28261f ? 0.11747262f : -0.046223022f)
            : (data[7 /* C8 */] <54.73513f ? 0.047461435f : -0.003337348f))
          : -0.10459664f)
        : (data[6 /* C7 */] <91.72775f
          ? 0.14884432f
          : (data[4 /* C5 */] <-2.8963966f ? 0.10527587f : -0.0145762395f))));
    return pred;
  }
}


class GBM_Model_Forest_4 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_4_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_4_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != -25.0f
      ? (data[9 /* C10 */] <-65.5f
        ? (data[7 /* C8 */] <92.18712f
          ? (data[5 /* C6 */] <96.86867f
            ? (data[4 /* C5 */] <-90.62162f ? -0.01841224f : -0.001799965f)
            : (data[5 /* C6 */] <97.015144f ? 0.16967353f : 0.02255609f))
          : (data[5 /* C6 */] <60.932877f
            ? (data[2 /* C3 */] <30.5f ? 0.0042073913f : -0.039743338f)
            : (data[1 /* C2 */] <31.176102f ? -0.089074455f : -0.013228609f)))
        : (data[5 /* C6 */] <-71.87284f
          ? (data[6 /* C7 */] <-40.625633f
            ? (data[5 /* C6 */] <-93.40716f ? -0.009001136f : 0.019463653f)
            : (data[4 /* C5 */] <-3.1241379f ? 0.0070977863f : -0.003088815f))
          : (data[7 /* C8 */] <-81.24981f
            ? (data[3 /* C4 */] <-65.62468f ? -0.01775562f : -0.002507173f)
            : (data[3 /* C4 */] <53.123474f ? -6.530185E-4f : 0.003945423f))))
      : (data[8 /* C9 */] <40.624863f
        ? (data[4 /* C5 */] <-38.89931f
          ? (data[9 /* C10 */] <20.0f
            ? (data[1 /* C2 */] <-49.564777f ? 0.05925383f : 0.15186577f)
            : (data[1 /* C2 */] <-58.881866f ? 0.16657166f : -0.01446437f))
          : (data[5 /* C6 */] <-1.3907776f
            ? (data[3 /* C4 */] <-43.958103f ? 0.06370512f : -0.04530521f)
            : (data[3 /* C4 */] <63.742546f ? 0.03569049f : 0.17510653f)))
        : (data[5 /* C6 */] <82.769936f
          ? (data[8 /* C9 */] <67.70169f
            ? (data[7 /* C8 */] <-32.666733f ? 2.7845494E-4f : -0.17084166f)
            : (data[4 /* C5 */] <45.458046f ? 0.038504887f : -0.10257362f))
          : 0.085962854f)));
    return pred;
  }
}


class GBM_Model_Forest_5 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_5_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_5_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != -55.0f
      ? (data[2 /* C3 */] <96.5f
        ? (data[9 /* C10 */] <-83.5f
          ? (data[2 /* C3 */] <-60.5f
            ? (data[2 /* C3 */] <-90.0f ? 0.009795488f : -0.02039232f)
            : (data[7 /* C8 */] <87.49544f ? -6.763543E-5f : -0.022667242f))
          : (data[5 /* C6 */] <-71.87344f
            ? (data[6 /* C7 */] <-81.24924f ? 0.017721385f : 0.0025561324f)
            : (data[7 /* C8 */] <-74.999275f ? -0.0038255944f : 7.2680134E-4f)))
        : (data[1 /* C2 */] <-2.3432617f
          ? (data[8 /* C9 */] <81.23553f
            ? (data[2 /* C3 */] <99.5f ? -0.012690989f : -0.04976185f)
            : (data[1 /* C2 */] <-80.15935f ? 0.046541546f : -0.09197825f))
          : (data[8 /* C9 */] <-81.087776f
            ? (data[3 /* C4 */] <71.78963f ? 0.08179976f : -0.035798673f)
            : (data[6 /* C7 */] <28.170288f ? 0.014407832f : -0.02170677f))))
      : (data[7 /* C8 */] <-84.96031f
        ? (data[4 /* C5 */] <53.575356f
          ? (data[3 /* C4 */] <15.370632f ? -0.017949779f : -0.13539693f)
          : -0.18040025f)
        : (data[4 /* C5 */] <-2.5457306f
          ? (data[3 /* C4 */] <82.70355f
            ? (data[3 /* C4 */] <-5.7132797f ? -0.011626656f : 0.047742214f)
            : (data[1 /* C2 */] <-31.945206f ? -0.014726717f : -0.16419974f))
          : (data[5 /* C6 */] <-92.00016f
            ? 0.09430759f
            : (data[6 /* C7 */] <-21.844185f ? -0.085872896f : -0.016675238f)))));
    return pred;
  }
}


class GBM_Model_Forest_6 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_6_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_6_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[9 /* C10 */] != 40.0f
      ? (data[6 /* C7 */] <99.60744f
        ? (data[4 /* C5 */] <43.749466f
          ? (data[4 /* C5 */] <-60.692554f
            ? (data[8 /* C9 */] <74.999725f ? -0.0032168704f : 0.007458565f)
            : (data[4 /* C5 */] <-19.897701f ? 0.004502256f : 2.4497285E-4f))
          : (data[6 /* C7 */] <-22.02787f
            ? (data[6 /* C7 */] <-98.76508f ? -0.022211652f : 0.0025588262f)
            : (data[6 /* C7 */] <29.286835f ? -0.00901053f : -7.743644E-4f)))
        : (data[7 /* C8 */] <-14.843521f
          ? (data[4 /* C5 */] <-56.65204f
            ? 0.17617734f
            : (data[5 /* C6 */] <42.042732f ? 0.066772506f : -0.107985f))
          : (data[3 /* C4 */] <81.30872f
            ? (data[7 /* C8 */] <44.216045f ? -0.070357405f : 0.034686968f)
            : 0.13717578f)))
      : (data[4 /* C5 */] <94.53006f
        ? (data[3 /* C4 */] <91.33375f
          ? (data[6 /* C7 */] <68.83969f
            ? (data[5 /* C6 */] <65.24921f ? -0.024052575f : 0.046426833f)
            : (data[3 /* C4 */] <65.42499f ? -0.10633873f : 0.05352709f))
          : 0.11449241f)
        : -0.15493499f));
    return pred;
  }
}


class GBM_Model_Forest_7 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_7_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_7_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[9 /* C10 */] != -29.0f
      ? (data[8 /* C9 */] <-20.703003f
        ? (data[8 /* C9 */] <-27.517548f
          ? (data[4 /* C5 */] <93.74035f
            ? (data[5 /* C6 */] <-18.748894f ? -0.0028012472f : 0.0018120516f)
            : (data[9 /* C10 */] <10.5f ? -0.001098485f : 0.03565797f))
          : (data[7 /* C8 */] <-82.81227f
            ? (data[3 /* C4 */] <-40.47364f ? -0.050727267f : 4.1849638E-4f)
            : (data[4 /* C5 */] <84.36627f ? 0.01793638f : -0.018940846f)))
        : (data[2 /* C3 */] <96.5f
          ? (data[5 /* C6 */] <70.30823f
            ? (data[9 /* C10 */] <-89.5f ? -0.008279625f : 7.003785E-4f)
            : (data[5 /* C6 */] <78.65748f ? -0.015487874f : -0.0027917526f))
          : (data[1 /* C2 */] <-7.812195f
            ? (data[4 /* C5 */] <21.410858f ? -0.016113028f : -0.056373145f)
            : (data[5 /* C6 */] <-93.32679f ? -0.1241595f : 5.460503E-4f))))
      : (data[7 /* C8 */] <9.375088f
        ? (data[4 /* C5 */] <-67.54446f
          ? (data[3 /* C4 */] <17.076149f
            ? (data[6 /* C7 */] <-27.781952f ? 0.0021129267f : 0.20065306f)
            : (data[5 /* C6 */] <-12.346848f ? 0.08398543f : -0.040297423f))
          : (data[7 /* C8 */] <-78.68534f
            ? (data[4 /* C5 */] <-17.59281f ? -0.066543765f : 0.13837063f)
            : (data[1 /* C2 */] <-68.51071f ? 0.05351813f : -0.06505944f)))
        : (data[4 /* C5 */] <95.95731f
          ? (data[6 /* C7 */] <-85.66023f
            ? (data[1 /* C2 */] <-28.986107f ? -0.120549545f : 0.033041675f)
            : (data[8 /* C9 */] <28.31694f ? 0.10604151f : 0.033899583f))
          : -0.11835528f)));
    return pred;
  }
}


class GBM_Model_Forest_8 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_8_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_8_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[9 /* C10 */] != 74.0f
      ? (data[8 /* C9 */] <-19.92176f
        ? (data[8 /* C9 */] <-27.74186f
          ? (data[6 /* C7 */] <-79.68653f
            ? (data[7 /* C8 */] <34.371933f ? 0.014601673f : -0.0070933094f)
            : (data[2 /* C3 */] <60.5f ? -0.0018377758f : 0.0049790526f))
          : (data[9 /* C10 */] <-11.5f
            ? (data[9 /* C10 */] <-28.5f ? 0.006178518f : -0.02325367f)
            : (data[6 /* C7 */] <-84.33987f ? -0.022756914f : 0.021880815f)))
        : (data[5 /* C6 */] <67.96814f
          ? (data[1 /* C2 */] <51.56108f
            ? (data[1 /* C2 */] <32.616318f ? 1.5474548E-5f : -0.011894985f)
            : (data[9 /* C10 */] <-59.5f ? -0.008700765f : 0.0072923126f))
          : (data[6 /* C7 */] <-98.436455f
            ? (data[1 /* C2 */] <34.378967f ? -0.028314365f : -0.11141208f)
            : (data[7 /* C8 */] <-87.48155f ? -0.023694666f : -0.0037622964f))))
      : (data[6 /* C7 */] <84.17798f
        ? (data[4 /* C5 */] <75.07353f
          ? (data[4 /* C5 */] <42.363358f
            ? (data[2 /* C3 */] <-89.0f ? -0.05848784f : 0.029461546f)
            : (data[8 /* C9 */] <59.202446f ? -0.0753404f : 0.037194237f))
          : (data[5 /* C6 */] <40.810318f
            ? (data[1 /* C2 */] <-12.299065f ? 0.19181703f : 0.07993328f)
            : -0.02685058f))
        : (data[6 /* C7 */] <91.72775f
          ? 0.13755569f
          : (data[4 /* C5 */] <-2.8963966f ? 0.095878094f : -0.013537631f))));
    return pred;
  }
}


class GBM_Model_Forest_9 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_9_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_9_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != 12.0f
      ? (data[2 /* C3 */] <-45.5f
        ? (data[7 /* C8 */] <-84.374374f
          ? (data[9 /* C10 */] <84.5f
            ? (data[6 /* C7 */] <81.24386f ? -0.002655929f : -0.03644782f)
            : (data[5 /* C6 */] <29.728027f ? -0.07562373f : -0.002630412f))
          : (data[9 /* C10 */] <-91.5f
            ? (data[4 /* C5 */] <-90.60827f ? -0.060692895f : -0.009542974f)
            : (data[3 /* C4 */] <96.87289f ? -7.530935E-4f : 0.02154353f)))
        : (data[6 /* C7 */] <-64.06197f
          ? (data[1 /* C2 */] <-29.686424f
            ? (data[5 /* C6 */] <0.0022201538f ? 0.0052804705f : -0.010178963f)
            : (data[3 /* C4 */] <34.375984f ? 0.003524032f : 0.018010326f))
          : (data[4 /* C5 */] <28.12265f
            ? (data[1 /* C2 */] <84.37366f ? 8.809896E-4f : 0.0098029785f)
            : (data[7 /* C8 */] <31.24701f ? -6.223703E-4f : -0.0068501076f))))
      : (data[5 /* C6 */] <70.897766f
        ? (data[1 /* C2 */] <-89.318825f
          ? -0.15671404f
          : (data[3 /* C4 */] <-79.60016f
            ? (data[1 /* C2 */] <-41.753693f ? -0.032766223f : 0.13434796f)
            : (data[4 /* C5 */] <75.007034f ? -0.040897965f : 0.021482658f)))
        : (data[6 /* C7 */] <-40.323864f
          ? (data[8 /* C9 */] <-35.5933f ? -0.1584043f : 0.040952384f)
          : (data[9 /* C10 */] <10.5f
            ? (data[5 /* C6 */] <81.96101f ? 0.06758122f : 0.2004092f)
            : (data[4 /* C5 */] <28.20504f ? -0.07930134f : 0.042198326f)))));
    return pred;
  }
}


class GBM_Model_Forest_10 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_10_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_10_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != -93.0f
      ? (data[2 /* C3 */] <-45.5f
        ? (data[7 /* C8 */] <-84.374374f
          ? (data[6 /* C7 */] <82.81211f
            ? (data[3 /* C4 */] <-84.38389f ? -0.030987725f : -0.0026163107f)
            : (data[9 /* C10 */] <30.5f ? -0.015265706f : -0.10037559f))
          : (data[7 /* C8 */] <-82.93395f
            ? (data[4 /* C5 */] <-81.23415f ? -0.09838289f : 0.045068484f)
            : (data[9 /* C10 */] <-89.5f ? -0.011639448f : -9.1727293E-4f)))
        : (data[2 /* C3 */] <-33.5f
          ? (data[8 /* C9 */] <-90.62492f
            ? (data[1 /* C2 */] <-62.47979f ? -0.09079379f : -0.0052971696f)
            : (data[5 /* C6 */] <90.588486f ? 0.006421412f : 0.032310344f))
          : (data[7 /* C8 */] <92.1828f
            ? (data[6 /* C7 */] <-74.99934f ? 0.004994459f : -1.9577266E-4f)
            : (data[0 /* C1 */] <0.5f ? -0.007075775f : -0.07998724f))))
      : (data[4 /* C5 */] <86.32704f
        ? (data[0 /* C1 */] <0.5f
          ? (data[6 /* C7 */] <67.13894f
            ? (data[6 /* C7 */] <17.533432f ? 0.02360643f : 0.078418724f)
            : (data[7 /* C8 */] <42.091576f ? 0.025903996f : -0.14614254f))
          : -0.09928147f)
        : (data[3 /* C4 */] <37.315815f ? -0.021344814f : -0.16075152f)));
    return pred;
  }
}


class GBM_Model_Forest_11 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_11_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_11_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != -74.0f
      ? (data[2 /* C3 */] <-45.5f
        ? (data[6 /* C7 */] <99.21681f
          ? (data[7 /* C8 */] <-26.562096f
            ? (data[9 /* C10 */] <50.5f ? -0.00125954f : -0.015189129f)
            : (data[7 /* C8 */] <-18.651993f ? 0.013843327f : -0.0013492906f))
          : (data[4 /* C5 */] <-73.42239f
            ? 0.16138163f
            : (data[1 /* C2 */] <81.15745f ? 0.004446916f : 0.1584813f)))
        : (data[2 /* C3 */] <-33.5f
          ? (data[8 /* C9 */] <-92.18736f
            ? (data[6 /* C7 */] <-4.7244797f ? 0.017497811f : -0.054038562f)
            : (data[5 /* C6 */] <87.464325f ? 0.005513276f : 0.025003288f))
          : (data[7 /* C8 */] <84.370514f
            ? (data[7 /* C8 */] <75.72818f ? 2.2535754E-4f : 0.008178547f)
            : (data[2 /* C3 */] <34.0f ? 0.0016096066f : -0.01204158f))))
      : (data[5 /* C6 */] <92.57703f
        ? (data[1 /* C2 */] <1.7831726f
          ? (data[8 /* C9 */] <-13.826675f
            ? (data[7 /* C8 */] <62.367783f ? 0.051149327f : -0.06400701f)
            : (data[7 /* C8 */] <-9.072556f ? -0.08451731f : 0.009012826f))
          : (data[6 /* C7 */] <70.33914f
            ? (data[3 /* C4 */] <-71.87137f ? -0.04192968f : 0.06768539f)
            : (data[3 /* C4 */] <-46.884598f ? 0.03513211f : -0.094626755f)))
        : (data[5 /* C6 */] <97.94648f ? 0.2007095f : 0.07879266f)));
    return pred;
  }
}


class GBM_Model_Forest_12 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_12_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_12_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[9 /* C10 */] != 40.0f
      ? (data[6 /* C7 */] <99.60744f
        ? (data[8 /* C9 */] <96.87463f
          ? (data[8 /* C9 */] <76.87961f
            ? (data[8 /* C9 */] <-19.851181f ? 0.0012242228f : -0.0014023544f)
            : (data[3 /* C4 */] <71.873604f ? 0.0016052476f : 0.016048871f))
          : (data[8 /* C9 */] <97.3385f
            ? (data[3 /* C4 */] <-12.524582f ? -5.777432E-4f : -0.07481951f)
            : (data[3 /* C4 */] <-9.400497f ? -0.019713566f : 0.012200646f)))
        : (data[6 /* C7 */] <99.64635f
          ? (data[4 /* C5 */] <-28.099344f ? 0.07013074f : 0.1551163f)
          : (data[6 /* C7 */] <99.742516f
            ? (data[5 /* C6 */] <-4.5823746f ? 0.0037960552f : -0.122573f)
            : (data[7 /* C8 */] <-14.784462f ? 0.07314849f : 6.555817E-4f))))
      : (data[1 /* C2 */] <68.55367f
        ? (data[1 /* C2 */] <61.979347f
          ? (data[4 /* C5 */] <95.30526f
            ? (data[5 /* C6 */] <-15.449081f ? -0.04970386f : 8.0557127E-4f)
            : -0.15838435f)
          : -0.17068546f)
        : (data[1 /* C2 */] <88.922554f
          ? (data[3 /* C4 */] <25.150257f
            ? (data[1 /* C2 */] <78.29295f ? -0.022981001f : 0.10256367f)
            : 0.1657764f)
          : (data[3 /* C4 */] <-19.640167f ? 0.06908414f : -0.121662825f))));
    return pred;
  }
}


class GBM_Model_Forest_13 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_13_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_13_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != -25.0f
      ? (data[3 /* C4 */] <8.983536f
        ? (data[1 /* C2 */] <91.404755f
          ? (data[1 /* C2 */] <-98.502106f
            ? (data[7 /* C8 */] <-96.87311f ? 0.10849055f : 0.0126362005f)
            : (data[3 /* C4 */] <7.278862f ? -0.0016158827f : -0.019137494f))
          : (data[4 /* C5 */] <21.872833f
            ? (data[6 /* C7 */] <-84.33728f ? -0.02927109f : 0.023484493f)
            : (data[3 /* C4 */] <-69.364624f ? 0.025124744f : -0.018895458f)))
        : (data[6 /* C7 */] <-96.09274f
          ? (data[1 /* C2 */] <-18.749374f
            ? (data[3 /* C4 */] <19.017326f ? 0.03403149f : -0.03840993f)
            : (data[1 /* C2 */] <31.324184f ? 0.021784388f : -0.026041111f))
          : (data[6 /* C7 */] <-80.77317f
            ? (data[4 /* C5 */] <-96.87068f ? 0.074374266f : 0.008198626f)
            : (data[4 /* C5 */] <-3.1233368f ? 0.0029674524f : -0.0011210835f))))
      : (data[8 /* C9 */] <40.624863f
        ? (data[4 /* C5 */] <-18.614517f
          ? (data[9 /* C10 */] <20.0f
            ? (data[3 /* C4 */] <54.95379f ? 0.089274816f : 0.18736278f)
            : (data[1 /* C2 */] <-58.815147f ? 0.12848172f : -0.0055883173f))
          : (data[5 /* C6 */] <-1.3907776f
            ? (data[1 /* C2 */] <37.612823f ? -0.04651246f : 0.051878955f)
            : (data[3 /* C4 */] <62.513756f ? 0.025612619f : 0.15967162f)))
        : (data[5 /* C6 */] <45.708344f
          ? (data[5 /* C6 */] <-12.196152f
            ? (data[8 /* C9 */] <75.07569f ? -0.05966097f : 0.0681711f)
            : (data[4 /* C5 */] <15.863937f ? -0.08424056f : -0.15593693f))
          : (data[1 /* C2 */] <-24.625034f
            ? -0.07323005f
            : (data[4 /* C5 */] <23.048973f ? 0.146127f : 0.002555774f)))));
    return pred;
  }
}


class GBM_Model_Forest_14 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_14_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_14_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != -22.0f
      ? (data[9 /* C10 */] <66.5f
        ? (data[4 /* C5 */] <-98.43621f
          ? (data[3 /* C4 */] <-67.18716f
            ? (data[7 /* C8 */] <40.643707f ? -0.046617266f : 0.017240647f)
            : (data[5 /* C6 */] <-84.35596f ? -0.03740703f : 0.022691254f))
          : (data[8 /* C9 */] <-95.31207f
            ? (data[9 /* C10 */] <41.5f ? -0.004306416f : -0.031250454f)
            : (data[8 /* C9 */] <8.447258f ? 0.0010546256f : -0.0018413708f)))
        : (data[9 /* C10 */] <79.5f
          ? (data[8 /* C9 */] <-54.68542f
            ? (data[8 /* C9 */] <-60.342976f ? 0.01947102f : 0.079497136f)
            : (data[9 /* C10 */] != 72.0f ? 0.0065584f : -0.026009712f))
          : (data[6 /* C7 */] <65.61551f
            ? (data[1 /* C2 */] <28.127426f ? -0.009905452f : 0.0040823137f)
            : (data[7 /* C8 */] <-74.995834f ? -0.025177425f : 0.020520555f))))
      : (data[8 /* C9 */] <35.937393f
        ? (data[9 /* C10 */] <-71.5f
          ? (data[7 /* C8 */] <50.019096f
            ? (data[5 /* C6 */] <-11.551075f ? -0.07530051f : -0.1630428f)
            : -0.035873696f)
          : (data[8 /* C9 */] <-90.73856f
            ? 0.08928419f
            : (data[4 /* C5 */] <-59.378513f ? -0.07486783f : -0.023376212f)))
        : (data[3 /* C4 */] <17.48188f
          ? (data[7 /* C8 */] <-85.06673f
            ? 0.12852086f
            : (data[5 /* C6 */] <-46.772552f ? -0.11647645f : -0.004769246f))
          : (data[3 /* C4 */] <63.76105f
            ? (data[8 /* C9 */] <73.21683f ? 0.06586502f : 0.19921842f)
            : (data[4 /* C5 */] <-11.632462f ? -0.07851074f : 0.08178839f)))));
    return pred;
  }
}


class GBM_Model_Forest_15 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_15_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_15_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != 33.0f
      ? (data[2 /* C3 */] <96.5f
        ? (data[3 /* C4 */] <8.592918f
          ? (data[7 /* C8 */] <53.124832f
            ? (data[1 /* C2 */] <-96.872505f ? 0.014161804f : -1.9145687E-4f)
            : (data[3 /* C4 */] <-45.703228f ? 0.0021117295f : -0.011706231f))
          : (data[6 /* C7 */] <-95.3115f
            ? (data[3 /* C4 */] <14.30578f ? 0.038459226f : -0.015070824f)
            : (data[6 /* C7 */] <-80.05296f ? 0.009531129f : 9.726813E-4f)))
        : (data[1 /* C2 */] <-2.3432617f
          ? (data[8 /* C9 */] <81.23553f
            ? (data[7 /* C8 */] <-93.731415f ? -0.09368279f : -0.014300537f)
            : (data[8 /* C9 */] <84.405716f ? -0.15643069f : -0.040104367f))
          : (data[8 /* C9 */] <-81.087776f
            ? (data[3 /* C4 */] <71.78963f ? 0.07309002f : -0.033400778f)
            : (data[1 /* C2 */] <-0.7054428f ? 0.123786494f : -0.001336137f))))
      : (data[5 /* C6 */] <-19.725437f
        ? (data[8 /* C9 */] <72.417725f
          ? (data[3 /* C4 */] <75.28094f
            ? (data[3 /* C4 */] <53.420815f ? 0.0062497016f : 0.1710256f)
            : -0.1252813f)
          : (data[7 /* C8 */] <-4.661339f ? -0.039629944f : -0.20028861f))
        : (data[4 /* C5 */] <93.83976f
          ? (data[5 /* C6 */] <19.796413f
            ? (data[7 /* C8 */] <-15.095055f ? 0.03982667f : 0.118417166f)
            : (data[7 /* C8 */] <65.538925f ? 0.014269013f : 0.11286069f))
          : -0.11887076f)));
    return pred;
  }
}


class GBM_Model_Forest_16 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_16_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_16_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != -55.0f
      ? (data[4 /* C5 */] <-61.32731f
        ? (data[6 /* C7 */] <96.09186f
          ? (data[8 /* C9 */] <76.55651f
            ? (data[6 /* C7 */] <89.96118f ? -0.0029812304f : -0.02200015f)
            : (data[2 /* C3 */] <-39.5f ? -0.009218038f : 0.013420809f))
          : (data[1 /* C2 */] <35.93718f
            ? (data[4 /* C5 */] <-99.27882f ? -0.07535901f : 0.007533124f)
            : (data[7 /* C8 */] <52.596107f ? 0.046799902f : 0.15215085f)))
        : (data[4 /* C5 */] <-19.735435f
          ? (data[4 /* C5 */] <-35.332367f
            ? (data[5 /* C6 */] <-81.245224f ? -0.012900378f : 0.0027389699f)
            : (data[9 /* C10 */] <80.5f ? 0.009856207f : -0.006221589f))
          : (data[4 /* C5 */] <-15.058319f
            ? (data[2 /* C3 */] <80.5f ? -0.014933523f : 0.028736806f)
            : (data[6 /* C7 */] <53.12622f ? 9.564771E-4f : -0.0035269612f))))
      : (data[1 /* C2 */] <46.28852f
        ? (data[7 /* C8 */] <-85.00681f
          ? (data[3 /* C4 */] <14.50145f ? -0.062280927f : -0.17390853f)
          : (data[5 /* C6 */] <76.04532f
            ? (data[7 /* C8 */] <-72.88362f ? 0.09795081f : -0.026618863f)
            : (data[5 /* C6 */] <80.05682f ? -0.15575506f : -0.06566848f)))
        : (data[8 /* C9 */] <74.40426f
          ? (data[8 /* C9 */] <36.82203f
            ? (data[5 /* C6 */] <67.353386f ? -0.005088757f : 0.14040016f)
            : (data[5 /* C6 */] <7.054928f ? 0.02009691f : -0.14108902f))
          : 0.12867038f)));
    return pred;
  }
}


class GBM_Model_Forest_17 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_17_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_17_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[9 /* C10 */] != -29.0f
      ? (data[9 /* C10 */] <66.5f
        ? (data[3 /* C4 */] <94.52908f
          ? (data[4 /* C5 */] <-98.43621f
            ? (data[7 /* C8 */] <-84.374374f ? -0.04274824f : 0.013551608f)
            : (data[5 /* C6 */] <68.749374f ? -4.3624273E-4f : -0.0039319783f))
          : (data[6 /* C7 */] <-93.7488f
            ? (data[4 /* C5 */] <71.84898f ? -0.065693274f : 0.08700504f)
            : (data[2 /* C3 */] <-79.5f ? 0.03667604f : 0.0070514223f)))
        : (data[9 /* C10 */] <79.5f
          ? (data[8 /* C9 */] <-54.68542f
            ? (data[8 /* C9 */] <-60.342976f ? 0.017735267f : 0.07164891f)
            : (data[9 /* C10 */] != 72.0f ? 0.005769124f : -0.023515968f))
          : (data[6 /* C7 */] <65.61551f
            ? (data[1 /* C2 */] <28.127426f ? -0.00902041f : 0.0032974742f)
            : (data[7 /* C8 */] <-74.995834f ? -0.022255618f : 0.019006794f))))
      : (data[7 /* C8 */] <9.375088f
        ? (data[4 /* C5 */] <-67.54446f
          ? (data[3 /* C4 */] <17.076149f
            ? (data[6 /* C7 */] <-27.781952f ? 0.0019755696f : 0.18214373f)
            : (data[5 /* C6 */] <-12.346848f ? 0.07426965f : -0.0371452f))
          : (data[7 /* C8 */] <-78.68534f
            ? (data[3 /* C4 */] <46.53511f ? -0.0040887645f : 0.1892018f)
            : (data[1 /* C2 */] <-68.51071f ? 0.04775843f : -0.05882293f)))
        : (data[4 /* C5 */] <95.95731f
          ? (data[6 /* C7 */] <-85.66023f
            ? (data[8 /* C9 */] <-57.083317f ? -0.117093824f : 0.03605923f)
            : (data[8 /* C9 */] <28.31694f ? 0.09573723f : 0.031099547f))
          : -0.106129f)));
    return pred;
  }
}


class GBM_Model_Forest_18 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_18_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_18_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != -93.0f
      ? (data[5 /* C6 */] <-71.48222f
        ? (data[6 /* C7 */] <-67.96816f
          ? (data[5 /* C6 */] <-93.536964f
            ? (data[2 /* C3 */] <80.5f ? -0.01933737f : 0.05327236f)
            : (data[9 /* C10 */] <-79.5f ? -0.020018956f : 0.02332836f))
          : (data[9 /* C10 */] <-67.5f
            ? (data[2 /* C3 */] <20.5f ? 0.0029998892f : -0.024575211f)
            : (data[8 /* C9 */] <-12.503578f ? -0.0020117566f : 0.0058059935f)))
        : (data[5 /* C6 */] <-44.68832f
          ? (data[6 /* C7 */] <53.123764f
            ? (data[1 /* C2 */] <68.73923f ? -0.0026945325f : 0.009789813f)
            : (data[1 /* C2 */] <-31.25122f ? -0.027014937f : -0.008237214f))
          : (data[3 /* C4 */] <53.123474f
            ? (data[2 /* C3 */] <-69.5f ? -0.004969078f : 2.2830478E-4f)
            : (data[7 /* C8 */] <87.49386f ? 0.0035874504f : -0.012000862f))))
      : (data[4 /* C5 */] <86.32704f
        ? (data[8 /* C9 */] <-97.30729f
          ? 0.15494332f
          : (data[0 /* C1 */] <0.5f
            ? (data[8 /* C9 */] <56.797714f ? 0.016519163f : 0.061012033f)
            : -0.08955668f))
        : (data[3 /* C4 */] <37.315815f ? -0.018410468f : -0.1464471f)));
    return pred;
  }
}


class GBM_Model_Forest_19 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_19_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_19_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != 12.0f
      ? (data[7 /* C8 */] <-26.952827f
        ? (data[7 /* C8 */] <-29.806206f
          ? (data[3 /* C4 */] <-68.74708f
            ? (data[1 /* C2 */] <96.8734f ? -0.0067208726f : 0.04956908f)
            : (data[5 /* C6 */] <-96.86925f ? -0.0144702075f : 6.669434E-4f))
          : (data[8 /* C9 */] <-18.743576f
            ? (data[9 /* C10 */] <-59.5f ? 0.03747753f : -0.0069844616f)
            : (data[8 /* C9 */] <-13.184692f ? -0.10850373f : -0.02084635f)))
        : (data[7 /* C8 */] <-26.45692f
          ? (data[8 /* C9 */] <-81.24963f
            ? (data[7 /* C8 */] <-26.75563f ? -0.0010701002f : 0.1798782f)
            : (data[2 /* C3 */] <-19.5f ? 0.057793133f : -0.0057318127f))
          : (data[7 /* C8 */] <47.638668f
            ? (data[9 /* C10 */] <-39.5f ? -6.310958E-4f : 0.0033226602f)
            : (data[3 /* C4 */] <90.619675f ? -0.0017450525f : 0.012501516f))))
      : (data[5 /* C6 */] <70.897766f
        ? (data[1 /* C2 */] <-92.02485f
          ? -0.15832914f
          : (data[3 /* C4 */] <-79.60016f
            ? (data[1 /* C2 */] <-40.69899f ? -0.008443453f : 0.116635144f)
            : (data[3 /* C4 */] <-71.18198f ? -0.11608591f : -0.025938483f)))
        : (data[1 /* C2 */] <33.99865f
          ? (data[6 /* C7 */] <-61.611862f
            ? -0.070584185f
            : (data[5 /* C6 */] <82.45431f ? 0.025131462f : 0.14154822f))
          : -0.050902944f)));
    return pred;
  }
}


class GBM_Model_Forest_20 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_20_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_20_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != -74.0f
      ? (data[3 /* C4 */] <99.60713f
        ? (data[3 /* C4 */] <98.0477f
          ? (data[3 /* C4 */] <96.50046f
            ? (data[5 /* C6 */] <-71.87284f ? 0.0022311527f : -4.5793617E-4f)
            : (data[0 /* C1 */] <0.5f ? -0.009683071f : -0.17542641f))
          : (data[9 /* C10 */] <44.5f
            ? (data[4 /* C5 */] <74.85994f ? 0.034403965f : -0.03206281f)
            : (data[2 /* C3 */] <-59.5f ? 0.043678537f : -0.04119752f)))
        : (data[7 /* C8 */] <-73.82756f
          ? (data[5 /* C6 */] <-34.37593f ? -0.04441553f : -0.17018048f)
          : (data[1 /* C2 */] <-6.3366165f
            ? (data[7 /* C8 */] <-46.35475f ? 0.07932432f : -0.067518614f)
            : (data[1 /* C2 */] <36.736137f ? 0.103003204f : -0.01841488f))))
      : (data[5 /* C6 */] <92.57703f
        ? (data[1 /* C2 */] <1.7831726f
          ? (data[8 /* C9 */] <-13.826675f
            ? (data[3 /* C4 */] <-59.377983f ? -0.054542016f : 0.046746545f)
            : (data[7 /* C8 */] <-9.072556f ? -0.07566979f : 0.008690696f))
          : (data[6 /* C7 */] <70.33914f
            ? (data[1 /* C2 */] <9.546527f ? 0.1569629f : 0.035804544f)
            : (data[9 /* C10 */] <-24.5f ? -0.111961365f : 0.0051922915f)))
        : (data[5 /* C6 */] <97.94648f ? 0.18260324f : 0.07088095f)));
    return pred;
  }
}


class GBM_Model_Forest_21 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_21_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_21_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[9 /* C10 */] != 40.0f
      ? (data[8 /* C9 */] <96.484024f
        ? (data[8 /* C9 */] <92.646454f
          ? (data[4 /* C5 */] <-60.936687f
            ? (data[3 /* C4 */] <-93.74631f ? -0.016148511f : -0.0011560678f)
            : (data[4 /* C5 */] <-20.702831f ? 0.0035102013f : -4.720435E-4f))
          : (data[1 /* C2 */] <-90.622635f
            ? (data[5 /* C6 */] <84.34701f ? 0.08651254f : -0.11884987f)
            : (data[6 /* C7 */] <-71.81121f ? 0.039768893f : -1.7906903E-4f)))
        : (data[5 /* C6 */] <60.155792f
          ? (data[5 /* C6 */] <55.151016f
            ? (data[7 /* C8 */] <25.014763f ? 0.0035022774f : -0.022292327f)
            : (data[2 /* C3 */] <-19.5f ? 0.1636181f : 0.02716613f))
          : (data[3 /* C4 */] <-73.44437f
            ? (data[3 /* C4 */] <-90.6066f ? -0.037172016f : 0.08841706f)
            : (data[3 /* C4 */] <-6.049286f ? -0.09368549f : -0.018826328f))))
      : (data[3 /* C4 */] <91.40414f
        ? (data[6 /* C7 */] <68.065506f
          ? (data[3 /* C4 */] <86.201454f
            ? (data[4 /* C5 */] <90.61855f ? -0.006295957f : -0.109367386f)
            : -0.13746591f)
          : (data[3 /* C4 */] <66.90902f
            ? (data[3 /* C4 */] <-54.25893f ? 0.0027322902f : -0.122311406f)
            : 0.04911377f))
        : (data[2 /* C3 */] <-13.5f ? 0.1872435f : -0.009256074f)));
    return pred;
  }
}


class GBM_Model_Forest_22 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_22_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_22_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != 62.0f
      ? (data[2 /* C3 */] <96.5f
        ? (data[8 /* C9 */] <49.218582f
          ? (data[8 /* C9 */] <37.560913f
            ? (data[9 /* C10 */] <90.5f ? 4.6058453E-4f : -0.0058617853f)
            : (data[9 /* C10 */] <-59.5f ? -0.019897873f : -0.0024891612f))
          : (data[8 /* C9 */] <50.80549f
            ? (data[1 /* C2 */] <34.37606f ? 0.034665994f : -0.0058730636f)
            : (data[4 /* C5 */] <46.872116f ? 0.0031413636f : -0.0040984973f)))
        : (data[1 /* C2 */] <-2.3432617f
          ? (data[1 /* C2 */] <-30.57061f
            ? (data[1 /* C2 */] <-33.82486f ? -0.016085358f : 0.06657616f)
            : (data[3 /* C4 */] <90.39521f ? -0.05051535f : 0.09009305f))
          : (data[8 /* C9 */] <87.47874f
            ? (data[3 /* C4 */] <-9.391838f ? 0.027636223f : -0.005217719f)
            : (data[4 /* C5 */] <-32.85713f ? -0.14436702f : -0.014073222f))))
      : (data[8 /* C9 */] <-84.76524f
        ? (data[5 /* C6 */] <-71.22796f
          ? 0.16103257f
          : (data[5 /* C6 */] <-22.920326f
            ? -0.045603484f
            : (data[9 /* C10 */] <64.0f ? 0.016263321f : 0.16087328f)))
        : (data[9 /* C10 */] <-95.5f
          ? 0.10148147f
          : (data[7 /* C8 */] <93.42124f
            ? (data[4 /* C5 */] <-84.290146f ? 0.041490912f : -0.03531357f)
            : -0.15910691f))));
    return pred;
  }
}


class GBM_Model_Forest_23 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_23_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_23_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != 81.0f
      ? (data[7 /* C8 */] <-26.952827f
        ? (data[7 /* C8 */] <-29.806206f
          ? (data[3 /* C4 */] <-68.74708f
            ? (data[1 /* C2 */] <96.8734f ? -0.0061139595f : 0.043036953f)
            : (data[5 /* C6 */] <-96.86925f ? -0.014259523f : 6.648535E-4f))
          : (data[3 /* C4 */] <-65.62218f
            ? (data[3 /* C4 */] <-76.783455f ? -0.0065416633f : 0.054160785f)
            : (data[3 /* C4 */] <-60.45086f ? -0.10659809f : -0.016247733f)))
        : (data[7 /* C8 */] <-26.45692f
          ? (data[7 /* C8 */] <-26.604017f
            ? (data[2 /* C3 */] <-89.5f ? 0.13246766f : -0.0038403806f)
            : (data[8 /* C9 */] <6.0418167f ? 0.13627861f : 0.021748723f))
          : (data[3 /* C4 */] <-56.25056f
            ? (data[4 /* C5 */] <-65.62367f ? -0.0070744082f : 0.005838218f)
            : (data[3 /* C4 */] <7.223942f ? -0.0028741562f : 0.0017778588f))))
      : (data[6 /* C7 */] <5.077614f
        ? (data[9 /* C10 */] <12.5f
          ? (data[6 /* C7 */] <-32.661957f
            ? (data[8 /* C9 */] <56.573296f ? 0.045740582f : -0.054288566f)
            : (data[4 /* C5 */] <70.036575f ? -0.03857201f : -0.16486344f))
          : (data[4 /* C5 */] <64.723625f
            ? (data[5 /* C6 */] <35.88739f ? -0.08380464f : -0.20122302f)
            : (data[3 /* C4 */] <-2.8802872f ? -0.16318102f : 0.10836501f)))
        : (data[7 /* C8 */] <-82.42943f
          ? (data[6 /* C7 */] <41.137688f ? 0.001664164f : -0.16986616f)
          : (data[7 /* C8 */] <-59.67615f
            ? (data[9 /* C10 */] <-9.0f ? 0.1748129f : 0.045674328f)
            : (data[4 /* C5 */] <-55.09931f ? 0.0868433f : -0.029143827f)))));
    return pred;
  }
}


class GBM_Model_Forest_24 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_24_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_24_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != -22.0f
      ? (data[3 /* C4 */] <99.60713f
        ? (data[4 /* C5 */] <43.749466f
          ? (data[6 /* C7 */] <95.31062f
            ? (data[6 /* C7 */] <89.2072f ? 7.6011673E-4f : -0.0074006356f)
            : (data[7 /* C8 */] <-84.374855f ? -0.034525037f : 0.013161417f))
          : (data[5 /* C6 */] <34.37506f
            ? (data[8 /* C9 */] <9.371658f ? 3.7210126E-4f : -0.007280919f)
            : (data[6 /* C7 */] <-18.744484f ? 0.007923098f : -0.0017254867f)))
        : (data[7 /* C8 */] <-73.82756f
          ? (data[1 /* C2 */] <24.39534f ? -0.021555759f : -0.18847896f)
          : (data[1 /* C2 */] <-6.3366165f
            ? (data[7 /* C8 */] <-46.35475f ? 0.07047916f : -0.06513139f)
            : (data[1 /* C2 */] <36.736137f ? 0.09799828f : -0.016564388f))))
      : (data[8 /* C9 */] <23.046814f
        ? (data[4 /* C5 */] <33.49478f
          ? (data[3 /* C4 */] <35.231544f
            ? (data[8 /* C9 */] <-59.4968f ? -0.01280502f : -0.10779483f)
            : (data[3 /* C4 */] <73.53224f ? 0.037651796f : -0.08261038f))
          : (data[7 /* C8 */] <-70.02707f
            ? -0.16415125f
            : (data[4 /* C5 */] <69.64627f ? 0.06089629f : -0.0077831466f)))
        : (data[4 /* C5 */] <-65.30719f
          ? (data[4 /* C5 */] <-86.13304f
            ? 0.011914481f
            : (data[5 /* C6 */] <-19.641766f ? -0.0025131495f : -0.15204416f))
          : (data[4 /* C5 */] <18.085045f
            ? (data[6 /* C7 */] <-90.08989f ? 0.19395998f : 0.044422746f)
            : (data[4 /* C5 */] <35.7658f ? -0.14279026f : 0.021496724f)))));
    return pred;
  }
}


class GBM_Model_Forest_25 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_25_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_25_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[9 /* C10 */] != -10.0f
      ? (data[4 /* C5 */] <-61.32731f
        ? (data[1 /* C2 */] <55.468018f
          ? (data[1 /* C2 */] <38.46399f
            ? (data[4 /* C5 */] <-63.750183f ? -8.9774554E-4f : -0.018170008f)
            : (data[6 /* C7 */] <96.8531f ? -0.017355056f : 0.09659198f))
          : (data[6 /* C7 */] <67.16911f
            ? (data[1 /* C2 */] <56.172848f ? 0.075840816f : -0.0018796028f)
            : (data[5 /* C6 */] <84.34336f ? 0.036063604f : -0.04944439f)))
        : (data[4 /* C5 */] <-19.735435f
          ? (data[8 /* C9 */] <17.187462f
            ? (data[1 /* C2 */] <-46.87326f ? -0.0021329282f : 0.008609775f)
            : (data[4 /* C5 */] <-39.88275f ? -0.006061627f : 0.004748067f))
          : (data[4 /* C5 */] <-15.058319f
            ? (data[2 /* C3 */] <80.5f ? -0.013520574f : 0.027561547f)
            : (data[7 /* C8 */] <-43.749607f ? -0.0024144005f : 0.0010991483f))))
      : (data[4 /* C5 */] <41.405746f
        ? (data[3 /* C4 */] <11.898109f
          ? (data[8 /* C9 */] <-45.41205f
            ? (data[2 /* C3 */] <40.5f ? -0.14750604f : 0.03448356f)
            : (data[3 /* C4 */] <0.5058594f ? 0.0029900994f : -0.10731364f))
          : (data[4 /* C5 */] <-90.080795f
            ? 0.1655294f
            : (data[1 /* C2 */] <76.57322f ? 0.012026008f : 0.16370176f)))
        : (data[5 /* C6 */] <33.141006f
          ? (data[3 /* C4 */] <22.546974f
            ? (data[5 /* C6 */] <-61.56573f ? -0.025449594f : -0.11560427f)
            : (data[4 /* C5 */] <63.84555f ? -0.11706178f : -0.19907154f))
          : (data[8 /* C9 */] <19.065563f
            ? (data[2 /* C3 */] <-28.5f ? 0.16157058f : 0.033164535f)
            : -0.06415611f))));
    return pred;
  }
}


class GBM_Model_Forest_26 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_26_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_26_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != -25.0f
      ? (data[8 /* C9 */] <49.609207f
        ? (data[8 /* C9 */] <36.752213f
          ? (data[9 /* C10 */] <92.5f
            ? (data[2 /* C3 */] <-89.5f ? 0.004841702f : -2.2142558E-4f)
            : (data[8 /* C9 */] <-18.805275f ? 0.0019187627f : -0.01953679f))
          : (data[9 /* C10 */] <-59.5f
            ? (data[1 /* C2 */] <-93.71406f ? 0.049360383f : -0.019539485f)
            : (data[2 /* C3 */] <-89.5f ? -0.026440639f : -0.0018914333f)))
        : (data[8 /* C9 */] <60.238434f
          ? (data[7 /* C8 */] <87.4997f
            ? (data[7 /* C8 */] <-3.3075256f ? 0.0043205777f : 0.018816713f)
            : (data[7 /* C8 */] <96.66508f ? -0.046982583f : 0.029817877f))
          : (data[2 /* C3 */] <4.5f
            ? (data[5 /* C6 */] <65.62016f ? -0.001830299f : -0.0131244f)
            : (data[2 /* C3 */] <43.5f ? 0.011552798f : -0.002449204f))))
      : (data[8 /* C9 */] <40.624863f
        ? (data[9 /* C10 */] <-23.5f
          ? (data[9 /* C10 */] <-93.5f
            ? (data[1 /* C2 */] <-12.094074f ? -9.582422E-5f : -0.011335895f)
            : (data[3 /* C4 */] <54.885544f ? 0.07820093f : 0.16057907f))
          : (data[6 /* C7 */] <90.402985f
            ? (data[4 /* C5 */] <-31.641464f ? 0.06542379f : 0.0018411528f)
            : -0.14064878f))
        : (data[5 /* C6 */] <82.769936f
          ? (data[8 /* C9 */] <67.70169f
            ? (data[7 /* C8 */] <-32.666733f ? 0.008116796f : -0.15034147f)
            : (data[4 /* C5 */] <45.458046f ? 0.03295527f : -0.08572422f))
          : 0.07511857f)));
    return pred;
  }
}


class GBM_Model_Forest_27 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_27_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_27_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != -8.0f
      ? (data[8 /* C9 */] <-96.48395f
        ? (data[6 /* C7 */] <45.311386f
          ? (data[6 /* C7 */] <32.82514f
            ? (data[3 /* C4 */] <18.75718f ? 0.0060718884f : -0.015986094f)
            : (data[2 /* C3 */] <0.5f ? 0.021791793f : 0.10172403f))
          : (data[1 /* C2 */] <-96.86196f
            ? (data[6 /* C7 */] <78.180214f ? 0.16008495f : 0.04720598f)
            : (data[4 /* C5 */] <84.32243f ? -0.024373487f : -0.09946556f)))
        : (data[8 /* C9 */] <-55.80571f
          ? (data[8 /* C9 */] <-63.750595f
            ? (data[6 /* C7 */] <37.50083f ? -0.0027531066f : 0.005828452f)
            : (data[3 /* C4 */] <53.11447f ? 0.005117767f : 0.02693872f))
          : (data[7 /* C8 */] <92.18711f
            ? (data[1 /* C2 */] <84.37259f ? -5.4761017E-4f : 0.005060803f)
            : (data[7 /* C8 */] <94.26229f ? -0.026097644f : -0.0014142359f))))
      : (data[3 /* C4 */] <94.13846f
        ? (data[4 /* C5 */] <-89.65011f
          ? (data[3 /* C4 */] <3.1559448f ? 0.1764719f : 0.015819145f)
          : (data[6 /* C7 */] <-51.39862f
            ? (data[4 /* C5 */] <28.909653f ? -0.05354543f : 0.013654806f)
            : (data[6 /* C7 */] <-30.119074f ? 0.08009355f : 0.008727405f)))
        : (data[4 /* C5 */] <-7.7612686f ? 0.19420917f : 0.077383496f)));
    return pred;
  }
}


class GBM_Model_Forest_28 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_28_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_28_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != -55.0f
      ? (data[9 /* C10 */] <66.5f
        ? (data[1 /* C2 */] <39.06212f
          ? (data[1 /* C2 */] <-48.936504f
            ? (data[1 /* C2 */] <-71.275665f ? 0.0010796562f : -0.0054208124f)
            : (data[8 /* C9 */] <-93.74958f ? -0.011620519f : 0.0024538413f))
          : (data[1 /* C2 */] <46.20308f
            ? (data[5 /* C6 */] <-87.49677f ? -0.04630918f : -0.0139785865f)
            : (data[3 /* C4 */] <96.87245f ? -9.479927E-4f : 0.028457033f)))
        : (data[9 /* C10 */] <79.5f
          ? (data[8 /* C9 */] <-54.68542f
            ? (data[8 /* C9 */] <-60.342976f ? 0.015293087f : 0.06322579f)
            : (data[9 /* C10 */] != 72.0f ? 0.0053584524f : -0.021573689f))
          : (data[6 /* C7 */] <65.61551f
            ? (data[8 /* C9 */] <87.488205f ? -0.0024126493f : -0.026917955f)
            : (data[8 /* C9 */] <6.246132f ? 0.0011230627f : 0.026254376f))))
      : (data[5 /* C6 */] <96.87381f
        ? (data[1 /* C2 */] <46.530113f
          ? (data[7 /* C8 */] <-86.563835f
            ? (data[3 /* C4 */] <16.05352f ? -0.053647593f : -0.16230826f)
            : (data[6 /* C7 */] <65.73146f ? -0.013967026f : -0.069445126f))
          : (data[5 /* C6 */] <78.922844f
            ? (data[8 /* C9 */] <73.41118f ? -0.013735232f : 0.13978182f)
            : 0.1258727f))
        : -0.15218236f));
    return pred;
  }
}


class GBM_Model_Forest_29 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_29_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_29_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != 33.0f
      ? (data[5 /* C6 */] <-71.87284f
        ? (data[6 /* C7 */] <-82.03046f
          ? (data[6 /* C7 */] <-99.84817f
            ? (data[3 /* C4 */] <18.782799f ? 0.006703116f : -0.07790496f)
            : (data[2 /* C3 */] <-59.5f ? -0.006535667f : 0.022684162f))
          : (data[4 /* C5 */] <76.553345f
            ? (data[8 /* C9 */] <-78.12308f ? -0.01042618f : 8.694853E-4f)
            : (data[4 /* C5 */] <85.34129f ? 0.02765912f : 0.0010251923f)))
        : (data[5 /* C6 */] <-65.83048f
          ? (data[8 /* C9 */] <98.43713f
            ? (data[3 /* C4 */] <-71.84045f ? -0.031316265f : -0.0017820748f)
            : (data[1 /* C2 */] <26.563438f ? -0.13947701f : -0.18908764f))
          : (data[8 /* C9 */] <74.999725f
            ? (data[8 /* C9 */] <66.796646f ? -3.419743E-4f : -0.007704633f)
            : (data[5 /* C6 */] <66.31528f ? 0.005561442f : -0.006082313f))))
      : (data[5 /* C6 */] <-19.725437f
        ? (data[8 /* C9 */] <82.91622f
          ? (data[6 /* C7 */] <75.81995f
            ? (data[3 /* C4 */] <75.28094f ? 0.032962568f : -0.09658645f)
            : (data[5 /* C6 */] <-34.92619f ? -0.13996823f : 0.04207923f))
          : -0.138101f)
        : (data[4 /* C5 */] <93.83976f
          ? (data[7 /* C8 */] <-47.658775f
            ? (data[9 /* C10 */] <-58.5f ? -0.1013737f : 0.03051344f)
            : (data[6 /* C7 */] <-84.197586f ? 0.15021303f : 0.048451517f))
          : -0.108207434f)));
    return pred;
  }
}


class GBM_Model_Forest_30 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_30_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_30_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != 12.0f
      ? (data[2 /* C3 */] <96.5f
        ? (data[8 /* C9 */] <49.218582f
          ? (data[8 /* C9 */] <46.887054f
            ? (data[4 /* C5 */] <93.74885f ? -3.260463E-4f : 0.006953896f)
            : (data[9 /* C10 */] <-59.5f ? -0.040318593f : -0.004058623f))
          : (data[8 /* C9 */] <59.533478f
            ? (data[4 /* C5 */] <-53.125027f ? -0.0059884735f : 0.012747238f)
            : (data[4 /* C5 */] <-87.49905f ? 0.011332863f : -8.076544E-4f)))
        : (data[1 /* C2 */] <-2.3432617f
          ? (data[1 /* C2 */] <-58.797966f
            ? (data[6 /* C7 */] <-49.99906f ? 0.034590337f : -0.019314649f)
            : (data[4 /* C5 */] <81.00029f ? -0.02351027f : -0.08965183f))
          : (data[6 /* C7 */] <18.752281f
            ? (data[6 /* C7 */] <0.22541046f ? 0.009885791f : 0.07072981f)
            : (data[3 /* C4 */] <87.40144f ? -0.020698162f : 0.06666602f))))
      : (data[4 /* C5 */] <76.17093f
        ? (data[4 /* C5 */] <23.315521f
          ? (data[1 /* C2 */] <1.9129105f
            ? (data[8 /* C9 */] <-80.958984f ? -0.12583756f : -0.02575371f)
            : (data[1 /* C2 */] <27.789286f ? 0.0881495f : -0.004289286f))
          : (data[4 /* C5 */] <25.57899f
            ? -0.19430915f
            : (data[1 /* C2 */] <-1.5057678f ? 3.1384632E-5f : -0.088858075f)))
        : (data[1 /* C2 */] <-37.517754f
          ? -0.07591328f
          : (data[7 /* C8 */] <0.23750305f
            ? 0.15479505f
            : (data[7 /* C8 */] <48.551918f ? -0.06815636f : 0.12553726f)))));
    return pred;
  }
}


class GBM_Model_Forest_31 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_31_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_31_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[9 /* C10 */] != -29.0f
      ? (data[9 /* C10 */] <66.5f
        ? (data[4 /* C5 */] <-98.43621f
          ? (data[3 /* C4 */] <-67.18716f
            ? (data[4 /* C5 */] <-98.73221f ? -0.03391893f : 0.064317726f)
            : (data[5 /* C6 */] <90.45768f ? 0.0112676965f : 0.080128595f))
          : (data[5 /* C6 */] <70.311844f
            ? (data[5 /* C6 */] <57.00644f ? -5.7133334E-4f : 0.0048588826f)
            : (data[4 /* C5 */] <-73.62917f ? -0.015225654f : -0.0017288569f)))
        : (data[8 /* C9 */] <-56.249737f
          ? (data[5 /* C6 */] <-28.125519f
            ? (data[8 /* C9 */] <-66.50841f ? -0.014348505f : 0.025704548f)
            : (data[7 /* C8 */] <-37.471275f ? -0.0010989825f : 0.02562849f))
          : (data[8 /* C9 */] <-2.5433617f
            ? (data[1 /* C2 */] <90.62194f ? -0.008581251f : 0.03607289f)
            : (data[3 /* C4 */] <93.7262f ? 0.004116478f : -0.023686267f))))
      : (data[7 /* C8 */] <16.4063f
        ? (data[3 /* C4 */] <67.49201f
          ? (data[5 /* C6 */] <75.437706f
            ? (data[2 /* C3 */] <40.5f ? -0.00442524f : -0.08099821f)
            : 0.07974862f)
          : (data[5 /* C6 */] <44.679237f
            ? (data[1 /* C2 */] <-14.426018f ? 0.1668905f : 0.025883429f)
            : -0.07067367f))
        : (data[7 /* C8 */] <47.294846f
          ? (data[3 /* C4 */] <68.27079f
            ? (data[5 /* C6 */] <35.136215f ? 0.14088632f : 0.041175228f)
            : -0.009988158f)
          : (data[7 /* C8 */] <96.37106f
            ? (data[7 /* C8 */] <82.6038f ? 0.039354473f : -0.03963723f)
            : 0.1538217f))));
    return pred;
  }
}


class GBM_Model_Forest_32 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_32_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_32_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != -93.0f
      ? (data[2 /* C3 */] <-53.5f
        ? (data[2 /* C3 */] != -74.0f
          ? (data[4 /* C5 */] <71.877f
            ? (data[6 /* C7 */] <-40.615063f ? -0.007239954f : -0.0012856359f)
            : (data[7 /* C8 */] <62.49981f ? 1.2483739E-4f : 0.022731679f))
          : (data[5 /* C6 */] <91.39469f
            ? (data[1 /* C2 */] <-6.72538f ? -0.005552886f : 0.029185442f)
            : (data[6 /* C7 */] <12.75296f ? 0.14617406f : 0.050107945f)))
        : (data[4 /* C5 */] <70.31163f
          ? (data[8 /* C9 */] <78.11856f
            ? (data[8 /* C9 */] <66.986176f ? 8.73493E-4f : -0.006215767f)
            : (data[3 /* C4 */] <-81.249466f ? 0.022619616f : 0.0028772352f))
          : (data[3 /* C4 */] <-85.93689f
            ? (data[6 /* C7 */] <12.510399f ? 0.002032596f : -0.040111136f)
            : (data[7 /* C8 */] <-96.87206f ? 0.02655955f : -0.0019801066f))))
      : (data[4 /* C5 */] <86.32704f
        ? (data[3 /* C4 */] <-89.19122f
          ? (data[9 /* C10 */] <-27.5f ? 0.033365987f : 0.1641784f)
          : (data[0 /* C1 */] <0.5f
            ? (data[5 /* C6 */] <30.442726f ? 0.008056515f : 0.04837574f)
            : -0.10095033f))
        : (data[3 /* C4 */] <37.315815f ? -0.01622661f : -0.13325837f)));
    return pred;
  }
}


class GBM_Model_Forest_33 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_33_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_33_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[9 /* C10 */] != 40.0f
      ? (data[6 /* C7 */] <99.60744f
        ? (data[8 /* C9 */] <96.87463f
          ? (data[8 /* C9 */] <76.87961f
            ? (data[3 /* C4 */] <-96.871216f ? -0.006323443f : 8.4159965E-6f)
            : (data[3 /* C4 */] <71.873604f ? 0.001175077f : 0.013527606f))
          : (data[8 /* C9 */] <97.3385f
            ? (data[3 /* C4 */] <-25.02095f ? 0.0050148615f : -0.06382318f)
            : (data[7 /* C8 */] <28.125961f ? 0.009126912f : -0.022403425f)))
        : (data[6 /* C7 */] <99.9706f
          ? (data[6 /* C7 */] <99.66201f
            ? (data[5 /* C6 */] <15.618141f ? 0.13708903f : -0.0067685014f)
            : (data[6 /* C7 */] <99.75572f ? -0.052075274f : 0.02003709f))
          : 0.12511373f))
      : (data[1 /* C2 */] <68.55367f
        ? (data[1 /* C2 */] <61.979347f
          ? (data[4 /* C5 */] <90.61855f
            ? (data[6 /* C7 */] <96.71037f ? -0.011826368f : -0.15673262f)
            : (data[2 /* C3 */] <-29.5f ? -0.047813334f : -0.1716972f))
          : -0.15224731f)
        : (data[6 /* C7 */] <-21.352974f
          ? (data[3 /* C4 */] <-21.158493f ? 0.16374323f : 0.01648342f)
          : (data[8 /* C9 */] <6.228836f
            ? (data[1 /* C2 */] <88.97624f ? 0.09401926f : -0.0075846016f)
            : -0.11339948f))));
    return pred;
  }
}


class GBM_Model_Forest_34 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_34_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_34_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != 37.0f
      ? (data[6 /* C7 */] <-82.03046f
        ? (data[6 /* C7 */] <-91.71659f
          ? (data[3 /* C4 */] <92.18514f
            ? (data[1 /* C2 */] <-18.749535f ? -0.010191421f : 0.0048109572f)
            : (data[3 /* C4 */] <96.443954f ? -0.07466573f : -0.009438117f))
          : (data[7 /* C8 */] <29.691025f
            ? (data[6 /* C7 */] <-82.63825f ? 0.012102147f : 0.048298072f)
            : (data[3 /* C4 */] <84.37562f ? 0.0020737236f : -0.0549075f)))
        : (data[8 /* C9 */] <98.43713f
          ? (data[1 /* C2 */] <84.37366f
            ? (data[1 /* C2 */] <72.850464f ? -2.1854925E-4f : -0.00569865f)
            : (data[4 /* C5 */] <3.0517578E-5f ? 0.010370088f : -0.004845888f))
          : (data[2 /* C3 */] <44.5f
            ? (data[5 /* C6 */] <18.610794f ? -0.01914152f : 0.029488869f)
            : (data[3 /* C4 */] <61.758377f ? -0.018194351f : -0.11973513f))))
      : (data[1 /* C2 */] <61.717888f
        ? (data[7 /* C8 */] <-85.19102f
          ? (data[7 /* C8 */] <-95.9092f
            ? -0.16865605f
            : (data[8 /* C9 */] <22.431824f ? -0.12188616f : 0.034269735f))
          : (data[9 /* C10 */] <-51.5f
            ? (data[8 /* C9 */] <77.94602f ? -0.014682128f : -0.13370717f)
            : (data[4 /* C5 */] <87.483284f ? 0.026049968f : 0.14019619f)))
        : (data[9 /* C10 */] <-67.5f
          ? (data[3 /* C4 */] <7.8258133f ? 0.2014484f : 0.19770573f)
          : (data[5 /* C6 */] <-38.225163f
            ? 0.1358797f
            : (data[1 /* C2 */] <77.42499f ? 0.106422864f : -0.018826354f)))));
    return pred;
  }
}


class GBM_Model_Forest_35 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_35_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_35_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != 62.0f
      ? (data[4 /* C5 */] <-61.32731f
        ? (data[6 /* C7 */] <96.09186f
          ? (data[2 /* C3 */] <92.5f
            ? (data[5 /* C6 */] <93.73826f ? -8.335842E-4f : -0.017759081f)
            : (data[7 /* C8 */] <-81.24003f ? -0.07834605f : -0.00811506f))
          : (data[1 /* C2 */] <35.93718f
            ? (data[1 /* C2 */] <29.613876f ? 0.0068244366f : -0.12855376f)
            : (data[7 /* C8 */] <52.596107f ? 0.03790181f : 0.13142546f)))
        : (data[3 /* C4 */] <-56.249825f
          ? (data[7 /* C8 */] <-43.749607f
            ? (data[8 /* C9 */] <-6.242546f ? -0.009454803f : 0.0036852085f)
            : (data[1 /* C2 */] <84.37412f ? 0.00401791f : 0.019012643f))
          : (data[5 /* C6 */] <85.93654f
            ? (data[5 /* C6 */] <68.50528f ? -8.6016174E-5f : -0.0073565613f)
            : (data[3 /* C4 */] <92.673706f ? 0.008224465f : -0.025268659f))))
      : (data[8 /* C9 */] <-6.0546265f
        ? (data[8 /* C9 */] <-20.871841f
          ? (data[8 /* C9 */] <-65.18515f
            ? (data[6 /* C7 */] <57.19574f ? 0.043295473f : -0.056095887f)
            : (data[4 /* C5 */] <67.839714f ? -0.016707262f : -0.16930248f))
          : (data[1 /* C2 */] <-14.105553f ? 0.16808963f : 0.03682654f))
        : (data[9 /* C10 */] <88.5f
          ? (data[9 /* C10 */] <-92.5f
            ? 0.07585187f
            : (data[6 /* C7 */] <-57.46002f ? -0.09897169f : -0.038318414f))
          : 0.093882374f)));
    return pred;
  }
}


class GBM_Model_Forest_36 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_36_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_36_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != -22.0f
      ? (data[3 /* C4 */] <99.60713f
        ? (data[3 /* C4 */] <98.0477f
          ? (data[3 /* C4 */] <96.50046f
            ? (data[3 /* C4 */] <93.430145f ? 1.6249118E-5f : 0.0078069526f)
            : (data[0 /* C1 */] <0.5f ? -0.008158163f : -0.1576318f))
          : (data[2 /* C3 */] <-59.5f
            ? (data[3 /* C4 */] <98.21849f ? 0.12721424f : 0.032593306f)
            : (data[5 /* C6 */] <-80.641464f ? -0.076479085f : 0.008312036f)))
        : (data[8 /* C9 */] <26.562428f
          ? (data[7 /* C8 */] <-82.23976f
            ? -0.14488067f
            : (data[2 /* C3 */] <70.5f ? -0.04574391f : 0.055903785f))
          : (data[6 /* C7 */] <73.38987f
            ? (data[6 /* C7 */] <41.7315f ? 0.04535424f : -0.12166199f)
            : 0.1347638f)))
      : (data[8 /* C9 */] <23.046814f
        ? (data[4 /* C5 */] <33.49478f
          ? (data[9 /* C10 */] <-67.5f
            ? (data[1 /* C2 */] <11.444504f ? -0.077203f : -0.18254566f)
            : (data[7 /* C8 */] <62.52217f ? -0.054708537f : 0.036202293f))
          : (data[7 /* C8 */] <-70.02707f
            ? -0.14904737f
            : (data[1 /* C2 */] <70.81421f ? 0.010639072f : 0.09303268f)))
        : (data[4 /* C5 */] <-65.30719f
          ? (data[4 /* C5 */] <-86.13304f
            ? 0.0109370705f
            : (data[5 /* C6 */] <-19.641766f ? -0.0023385957f : -0.137504f))
          : (data[1 /* C2 */] <43.124832f
            ? (data[1 /* C2 */] <-1.4661484f ? 0.023221783f : 0.12044254f)
            : (data[1 /* C2 */] <67.552925f ? -0.11014324f : 0.055509817f)))));
    return pred;
  }
}


class GBM_Model_Forest_37 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_37_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_37_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != 81.0f
      ? (data[1 /* C2 */] <99.60771f
        ? (data[2 /* C3 */] <68.5f
          ? (data[2 /* C3 */] <48.5f
            ? (data[2 /* C3 */] <4.5f ? -5.7712005E-4f : 0.002173792f)
            : (data[6 /* C7 */] <-31.249817f ? -0.011414171f : 7.725255E-4f))
          : (data[3 /* C4 */] <-90.62429f
            ? (data[6 /* C7 */] <-71.87439f ? 0.060594205f : 0.009090528f)
            : (data[8 /* C9 */] <-3.1317215f ? 0.00471906f : -0.0025918772f)))
        : (data[4 /* C5 */] <80.46774f
          ? (data[1 /* C2 */] <99.9648f
            ? (data[3 /* C4 */] <-61.170094f ? 0.049002957f : -0.036154974f)
            : 0.09358677f)
          : (data[2 /* C3 */] <12.0f ? -0.2050638f : -0.04219178f)))
      : (data[7 /* C8 */] <-83.593124f
        ? (data[6 /* C7 */] <23.261993f
          ? (data[9 /* C10 */] <-9.5f ? -0.092462234f : 0.061752096f)
          : -0.14181644f)
        : (data[7 /* C8 */] <-23.126143f
          ? (data[9 /* C10 */] <-11.5f
            ? (data[4 /* C5 */] <70.2052f ? 0.11701847f : -0.0718842f)
            : (data[4 /* C5 */] <60.929794f ? -0.07557127f : 0.096327275f))
          : (data[9 /* C10 */] <-91.5f
            ? -0.13083136f
            : (data[3 /* C4 */] <84.12668f ? -0.026666295f : 0.0534287f)))));
    return pred;
  }
}


class GBM_Model_Forest_38 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_38_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_38_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != 36.0f
      ? (data[2 /* C3 */] <96.5f
        ? (data[1 /* C2 */] <32.031006f
          ? (data[1 /* C2 */] <27.905113f
            ? (data[7 /* C8 */] <-34.374657f ? -0.0017740276f : 0.0015137322f)
            : (data[0 /* C1 */] <0.5f ? 0.015352282f : -0.0820419f))
          : (data[1 /* C2 */] <46.367863f
            ? (data[5 /* C6 */] <56.245697f ? -0.009970925f : 0.0054884446f)
            : (data[9 /* C10 */] <-19.5f ? -0.0022290405f : 0.002415425f)))
        : (data[1 /* C2 */] <-2.3432617f
          ? (data[8 /* C9 */] <81.23553f
            ? (data[2 /* C3 */] <99.5f ? -0.004311402f : -0.03807931f)
            : (data[5 /* C6 */] <-2.8676147f ? -0.009871757f : -0.10004472f))
          : (data[8 /* C9 */] <-81.087776f
            ? (data[4 /* C5 */] <-20.371006f ? -0.001990927f : 0.07778668f)
            : (data[5 /* C6 */] <-93.32584f ? -0.08486384f : 0.0024410503f))))
      : (data[1 /* C2 */] <86.32674f
        ? (data[1 /* C2 */] <67.588615f
          ? (data[7 /* C8 */] <46.697853f
            ? (data[7 /* C8 */] <-78.97352f ? -0.0590082f : 0.008108421f)
            : (data[5 /* C6 */] <-25.404228f ? 0.018394824f : -0.09285564f))
          : (data[7 /* C8 */] <38.919357f
            ? (data[4 /* C5 */] <36.219185f ? -0.20207177f : -0.09925948f)
            : 0.040779345f))
        : (data[5 /* C6 */] <-45.038155f
          ? -0.041472536f
          : (data[4 /* C5 */] <46.845024f ? 0.061771046f : 0.19694974f))));
    return pred;
  }
}


class GBM_Model_Forest_39 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_39_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_39_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[9 /* C10 */] != -10.0f
      ? (data[1 /* C2 */] <99.60771f
        ? (data[5 /* C6 */] <-71.87284f
          ? (data[4 /* C5 */] <-39.06197f
            ? (data[5 /* C6 */] <-85.05967f ? -0.010494192f : 0.006639395f)
            : (data[7 /* C8 */] <40.62491f ? 0.007727338f : -0.003808559f))
          : (data[5 /* C6 */] <-45.017906f
            ? (data[6 /* C7 */] <53.123764f ? 3.333703E-5f : -0.013624425f)
            : (data[6 /* C7 */] <-25.000061f ? -0.0010883183f : 0.0012254695f)))
        : (data[4 /* C5 */] <80.46774f
          ? (data[6 /* C7 */] <86.6224f
            ? (data[2 /* C3 */] <80.0f ? -0.0011991281f : -0.13392079f)
            : 0.09199458f)
          : (data[5 /* C6 */] <-17.725784f ? -0.032197207f : -0.19046263f)))
      : (data[4 /* C5 */] <25.390327f
        ? (data[3 /* C4 */] <16.180542f
          ? (data[8 /* C9 */] <-45.41205f
            ? (data[2 /* C3 */] <40.5f ? -0.1278395f : 0.03132236f)
            : (data[3 /* C4 */] <-14.839798f ? 0.018629227f : -0.068169005f))
          : (data[3 /* C4 */] <24.587418f
            ? 0.16116199f
            : (data[2 /* C3 */] <-8.5f ? -0.015146959f : 0.064414f)))
        : (data[5 /* C6 */] <24.245384f
          ? (data[4 /* C5 */] <76.260574f
            ? (data[3 /* C4 */] <-25.38845f ? -0.022435576f : -0.09887554f)
            : (data[2 /* C3 */] <36.0f ? -0.1865171f : -0.07575772f))
          : (data[8 /* C9 */] <42.338707f
            ? (data[7 /* C8 */] <-43.39692f ? -0.035049926f : 0.088856734f)
            : -0.09198181f))));
    return pred;
  }
}


class GBM_Model_Forest_40 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_40_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_40_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != 14.0f
      ? (data[3 /* C4 */] <-97.26482f
        ? (data[8 /* C9 */] <82.030945f
          ? (data[1 /* C2 */] <68.71863f
            ? (data[4 /* C5 */] <43.824364f ? 0.0017516802f : -0.021043414f)
            : (data[5 /* C6 */] <84.24898f ? -0.042346988f : 0.043005083f))
          : (data[1 /* C2 */] <60.128372f
            ? (data[1 /* C2 */] <-60.63779f ? 0.08077909f : -0.013161047f)
            : (data[7 /* C8 */] <-18.557392f ? 0.019143501f : 0.14753903f)))
        : (data[3 /* C4 */] <-91.87092f
          ? (data[7 /* C8 */] <-96.8743f
            ? (data[4 /* C5 */] <-34.371986f ? 0.14477944f : 0.02219269f)
            : (data[7 /* C8 */] <-75.34361f ? -0.026854822f : 0.0064045093f))
          : (data[6 /* C7 */] <-95.3115f
            ? (data[1 /* C2 */] <-18.74916f ? -0.0147911105f : 0.0028505437f)
            : (data[6 /* C7 */] <-83.10465f ? 0.003907914f : -2.1147927E-4f))))
      : (data[9 /* C10 */] <-65.5f
        ? (data[4 /* C5 */] <16.86325f
          ? (data[8 /* C9 */] <-45.10394f
            ? 0.10641173f
            : (data[4 /* C5 */] <-16.147068f ? -0.08689138f : 0.076779194f))
          : (data[1 /* C2 */] <2.0901413f ? -0.1724656f : -0.0378662f))
        : (data[3 /* C4 */] <-86.76863f
          ? (data[1 /* C2 */] <1.0720329f
            ? (data[4 /* C5 */] <15.093906f ? 0.20083535f : 0.12371086f)
            : 0.067967765f)
          : (data[5 /* C6 */] <-66.86161f
            ? (data[4 /* C5 */] <-40.83582f ? -0.034395643f : 0.11243759f)
            : (data[7 /* C8 */] <87.361984f ? 0.01816535f : -0.1277528f)))));
    return pred;
  }
}


class GBM_Model_Forest_41 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_41_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_41_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != -25.0f
      ? (data[4 /* C5 */] <-61.32731f
        ? (data[4 /* C5 */] <-62.08261f
          ? (data[1 /* C2 */] <95.31091f
            ? (data[8 /* C9 */] <74.9941f ? -0.0026564442f : 0.00539104f)
            : (data[6 /* C7 */] <-87.500175f ? -0.09671124f : 0.021095911f))
          : (data[2 /* C3 */] <52.5f
            ? (data[8 /* C9 */] <-74.79236f ? 0.08236304f : -0.017153384f)
            : (data[4 /* C5 */] <-61.80885f ? -0.14574552f : -0.037444293f)))
        : (data[4 /* C5 */] <-19.735435f
          ? (data[6 /* C7 */] <-92.18655f
            ? (data[1 /* C2 */] <-59.372967f ? -0.047919206f : -0.0012760024f)
            : (data[4 /* C5 */] <-22.337254f ? 0.0023340748f : 0.015683034f))
          : (data[4 /* C5 */] <-15.058319f
            ? (data[1 /* C2 */] <-78.11247f ? 0.022669494f : -0.012489881f)
            : (data[4 /* C5 */] <-9.66502f ? 0.006985309f : -4.491267E-4f))))
      : (data[4 /* C5 */] <-56.05394f
        ? (data[7 /* C8 */] <-2.6857224f
          ? (data[9 /* C10 */] <21.5f
            ? (data[3 /* C4 */] <-13.102913f ? 0.18072426f : 0.039934475f)
            : (data[4 /* C5 */] <-82.46104f ? -0.022887617f : -0.13598228f))
          : (data[1 /* C2 */] <-40.76768f
            ? 0.049990613f
            : (data[9 /* C10 */] <13.5f ? 0.12436968f : 0.18545249f)))
        : (data[5 /* C6 */] <59.606438f
          ? (data[7 /* C8 */] <-14.174599f
            ? (data[7 /* C8 */] <-80.88491f ? -0.058057997f : 0.040311936f)
            : (data[8 /* C9 */] <-11.380539f ? -5.244616E-4f : -0.061529208f))
          : (data[5 /* C6 */] <67.29141f
            ? 0.18445757f
            : (data[9 /* C10 */] <-57.5f ? 0.14037554f : 0.027063074f)))));
    return pred;
  }
}


class GBM_Model_Forest_42 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_42_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_42_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != 12.0f
      ? (data[6 /* C7 */] <-82.03046f
        ? (data[8 /* C9 */] <-86.71836f
          ? (data[7 /* C8 */] <48.43692f
            ? (data[2 /* C3 */] <50.5f ? -0.01985406f : 0.041963715f)
            : (data[1 /* C2 */] <-27.443474f ? -0.0061564576f : -0.07004228f))
          : (data[3 /* C4 */] <84.3729f
            ? (data[6 /* C7 */] <-85.682495f ? 0.002879073f : 0.016669123f)
            : (data[5 /* C6 */] <-74.908966f ? 0.029043404f : -0.023454586f)))
        : (data[3 /* C4 */] <95.31032f
          ? (data[2 /* C3 */] <4.5f
            ? (data[2 /* C3 */] <-0.5f ? -7.014704E-4f : -0.01106277f)
            : (data[7 /* C8 */] <34.37494f ? 0.0024326672f : -0.002921753f))
          : (data[3 /* C4 */] <96.00611f
            ? (data[7 /* C8 */] <-28.156143f ? -0.010782209f : 0.059358682f)
            : (data[2 /* C3 */] <-59.5f ? 0.027317256f : -0.0070243212f))))
      : (data[5 /* C6 */] <70.897766f
        ? (data[1 /* C2 */] <-89.318825f
          ? -0.12889053f
          : (data[3 /* C4 */] <-88.969955f
            ? 0.09044669f
            : (data[4 /* C5 */] <90.54486f ? -0.027448859f : 0.08040342f)))
        : (data[8 /* C9 */] <-41.614666f
          ? (data[4 /* C5 */] <-44.921703f ? 0.022926774f : -0.11681935f)
          : (data[1 /* C2 */] <-25.709175f
            ? (data[7 /* C8 */] <-15.058033f ? 0.18533175f : 0.06151782f)
            : (data[3 /* C4 */] <23.309624f ? -0.08039769f : 0.07576103f)))));
    return pred;
  }
}


class GBM_Model_Forest_43 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_43_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_43_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[9 /* C10 */] != 74.0f
      ? (data[8 /* C9 */] <-20.703003f
        ? (data[8 /* C9 */] <-23.800522f
          ? (data[1 /* C2 */] <-95.310036f
            ? (data[6 /* C7 */] <96.87311f ? -0.012852011f : 0.10014141f)
            : (data[5 /* C6 */] <87.49901f ? 1.4275986E-4f : 0.008536733f))
          : (data[7 /* C8 */] <-35.93859f
            ? (data[1 /* C2 */] <-53.18544f ? 0.046140984f : -0.016266227f)
            : (data[4 /* C5 */] <-40.619648f ? 0.05837029f : 0.009421502f)))
        : (data[5 /* C6 */] <67.96814f
          ? (data[2 /* C3 */] <44.5f
            ? (data[1 /* C2 */] <93.747345f ? 6.684415E-4f : 0.014239553f)
            : (data[7 /* C8 */] <34.375328f ? -7.126649E-5f : -0.008934263f))
          : (data[6 /* C7 */] <-98.436455f
            ? (data[1 /* C2 */] <34.378967f ? -0.020760804f : -0.100117706f)
            : (data[6 /* C7 */] <75.17556f ? -0.002226235f : -0.015871717f))))
      : (data[7 /* C8 */] <56.64044f
        ? (data[8 /* C9 */] <63.882713f
          ? (data[7 /* C8 */] <34.69731f
            ? (data[5 /* C6 */] <-43.961437f ? -0.03004289f : 0.019962745f)
            : (data[2 /* C3 */] <-28.5f ? 0.016249632f : 0.128312f))
          : (data[1 /* C2 */] <55.24276f
            ? (data[8 /* C9 */] <74.61838f ? 0.16019122f : 0.06911062f)
            : -0.033164226f))
        : (data[2 /* C3 */] <1.0f
          ? (data[4 /* C5 */] <5.61372f
            ? (data[3 /* C4 */] <-20.488197f ? -0.09525364f : 0.064396776f)
            : (data[3 /* C4 */] <9.614357f ? 0.15373993f : 0.012529383f))
          : (data[8 /* C9 */] <-4.289425f
            ? (data[2 /* C3 */] <61.0f ? 0.068292186f : -0.051792648f)
            : (data[7 /* C8 */] <79.2832f ? -0.16017866f : -0.03206644f)))));
    return pred;
  }
}


class GBM_Model_Forest_44 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_44_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_44_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[9 /* C10 */] != 93.0f
      ? (data[9 /* C10 */] <66.5f
        ? (data[1 /* C2 */] <39.06212f
          ? (data[4 /* C5 */] <45.31195f
            ? (data[7 /* C8 */] <-21.874733f ? -7.938661E-4f : 0.0029262095f)
            : (data[4 /* C5 */] <51.29332f ? -0.013289626f : -6.809175E-4f))
          : (data[1 /* C2 */] <46.20308f
            ? (data[5 /* C6 */] <-87.49677f ? -0.04140982f : -0.012185851f)
            : (data[3 /* C4 */] <96.87245f ? -9.2975114E-4f : 0.025529904f)))
        : (data[3 /* C4 */] <97.65404f
          ? (data[5 /* C6 */] <-98.4317f
            ? (data[8 /* C9 */] <40.617783f ? 0.011676353f : 0.07419463f)
            : (data[1 /* C2 */] <53.12432f ? 1.1462856E-5f : 0.0084318835f))
          : (data[7 /* C8 */] <-87.49779f
            ? 0.08894411f
            : (data[6 /* C7 */] <86.48182f ? -0.055127453f : 0.0836282f))))
      : (data[1 /* C2 */] <54.686783f
        ? (data[3 /* C4 */] <70.529175f
          ? (data[3 /* C4 */] <55.22278f
            ? (data[5 /* C6 */] <87.491516f ? -0.015391413f : 0.08399561f)
            : (data[4 /* C5 */] <27.855995f ? -0.1787316f : 0.015013047f))
          : (data[2 /* C3 */] <-59.0f
            ? 4.0905643E-4f
            : (data[7 /* C8 */] <54.548744f ? 0.15202567f : 0.01943951f)))
        : (data[6 /* C7 */] <54.880806f
          ? (data[1 /* C2 */] <92.77624f
            ? (data[6 /* C7 */] <-60.95858f ? -0.046042636f : -0.123814456f)
            : 0.028610846f)
          : (data[5 /* C6 */] <-30.74001f ? -0.08613916f : 0.09683357f))));
    return pred;
  }
}


class GBM_Model_Forest_45 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_45_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_45_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[9 /* C10 */] != -3.0f
      ? (data[1 /* C2 */] <-70.31056f
        ? (data[8 /* C9 */] <17.968712f
          ? (data[8 /* C9 */] <-6.914978f
            ? (data[7 /* C8 */] <37.494133f ? 0.0057290974f : -0.0072780503f)
            : (data[5 /* C6 */] <-96.839066f ? -0.05103399f : 0.016123239f))
          : (data[7 /* C8 */] <-96.86838f
            ? (data[2 /* C3 */] <-19.5f ? -0.015718479f : 0.067077495f)
            : (data[8 /* C9 */] <30.797565f ? -0.017038753f : -7.4468023E-4f)))
        : (data[1 /* C2 */] <-46.360874f
          ? (data[7 /* C8 */] <-87.49935f
            ? (data[1 /* C2 */] <-67.69067f ? 0.021189857f : -0.03086545f)
            : (data[9 /* C10 */] <-29.5f ? 0.003711731f : -0.005833126f))
          : (data[9 /* C10 */] <92.5f
            ? (data[8 /* C9 */] <96.86784f ? 6.1934703E-4f : -0.009712405f)
            : (data[6 /* C7 */] <3.1246262f ? -0.01705374f : 0.0035964435f))))
      : (data[1 /* C2 */] <-92.96634f
        ? (data[5 /* C6 */] <-21.479897f ? -0.19876815f : -0.020962225f)
        : (data[4 /* C5 */] <-89.67435f
          ? (data[3 /* C4 */] <-0.19665146f ? 0.1599675f : 0.03394631f)
          : (data[5 /* C6 */] <-63.405968f
            ? (data[1 /* C2 */] <42.473877f ? 0.020569768f : 0.15027483f)
            : (data[8 /* C9 */] <-53.176926f ? 0.03812803f : -0.0071185264f)))));
    return pred;
  }
}


class GBM_Model_Forest_46 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_46_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_46_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[9 /* C10 */] != -29.0f
      ? (data[8 /* C9 */] <-96.48395f
        ? (data[6 /* C7 */] <69.52977f
          ? (data[7 /* C8 */] <-68.756f
            ? (data[2 /* C3 */] <50.5f ? -0.008634242f : -0.06595189f)
            : (data[4 /* C5 */] <-90.62723f ? 0.055148542f : 0.0018953335f))
          : (data[6 /* C7 */] <86.863686f
            ? (data[5 /* C6 */] <-6.1309433f ? -0.09339893f : -0.015996628f)
            : (data[5 /* C6 */] <-12.338898f ? 0.042324886f : -0.03334947f)))
        : (data[8 /* C9 */] <-20.500069f
          ? (data[8 /* C9 */] <-27.62352f
            ? (data[4 /* C5 */] <93.74037f ? -2.4496115E-4f : 0.01652219f)
            : (data[4 /* C5 */] <84.36597f ? 0.010940727f : -0.022593996f))
          : (data[1 /* C2 */] <-98.43497f
            ? (data[7 /* C8 */] <-43.748737f ? 0.03722018f : 6.7997084E-4f)
            : (data[5 /* C6 */] <68.74579f ? -1.8659174E-4f : -0.0043483214f))))
      : (data[7 /* C8 */] <16.4063f
        ? (data[1 /* C2 */] <38.368965f
          ? (data[4 /* C5 */] <73.173546f
            ? (data[4 /* C5 */] <-67.475235f ? 0.061107878f : -0.015564537f)
            : 0.14973778f)
          : (data[1 /* C2 */] <63.933567f
            ? (data[8 /* C9 */] <22.140396f ? -0.069347076f : -0.18907656f)
            : (data[4 /* C5 */] <34.437714f ? 0.053237457f : -0.06898744f)))
        : (data[8 /* C9 */] <90.475494f
          ? (data[7 /* C8 */] <96.08963f
            ? (data[7 /* C8 */] <83.72417f ? 0.06480112f : -0.04642931f)
            : 0.17569059f)
          : -0.086135395f)));
    return pred;
  }
}


class GBM_Model_Forest_47 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_47_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_47_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C3 */] != -55.0f
      ? (data[6 /* C7 */] <99.60744f
        ? (data[9 /* C10 */] <-87.5f
          ? (data[3 /* C4 */] <-59.374775f
            ? (data[7 /* C8 */] <68.74596f ? -0.006362209f : -0.0441092f)
            : (data[2 /* C3 */] <-49.5f ? -0.00946704f : 0.0034744272f))
          : (data[5 /* C6 */] <-71.87284f
            ? (data[2 /* C3 */] <60.5f ? 7.159905E-4f : 0.008689808f)
            : (data[5 /* C6 */] <-28.904942f ? -0.002335872f : 6.733491E-4f)))
        : (data[5 /* C6 */] <53.12468f
          ? (data[4 /* C5 */] <70.67754f
            ? (data[5 /* C6 */] <-82.21741f ? -0.069468714f : 0.05822207f)
            : -0.058720358f)
          : (data[4 /* C5 */] <62.188904f
            ? (data[8 /* C9 */] <-26.237991f ? -0.19134675f : -0.026291559f)
            : 0.11540964f)))
      : (data[4 /* C5 */] <-0.39059448f
        ? (data[3 /* C4 */] <82.70355f
          ? (data[4 /* C5 */] <-16.886513f
            ? (data[6 /* C7 */] <74.9298f ? 0.010915598f : -0.07456652f)
            : (data[7 /* C8 */] <1.3658371f ? 0.17423527f : 0.03375652f))
          : (data[7 /* C8 */] <-0.9687233f ? -0.13149609f : -7.6725724E-4f))
        : (data[6 /* C7 */] <-7.5182877f
          ? (data[1 /* C2 */] <3.224823f
            ? (data[7 /* C8 */] <-53.73446f ? -5.976017E-5f : -0.12977964f)
            : (data[9 /* C10 */] <11.0f ? -0.07252524f : 0.045847997f))
          : (data[6 /* C7 */] <8.291104f
            ? (data[5 /* C6 */] <27.668427f ? 0.164646f : -0.007777361f)
            : (data[7 /* C8 */] <21.57647f ? -0.05387181f : 0.005968697f)))));
    return pred;
  }
}


class GBM_Model_Forest_48 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_48_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_48_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[9 /* C10 */] != 5.0f
      ? (data[3 /* C4 */] <-97.26482f
        ? (data[4 /* C5 */] <76.561554f
          ? (data[5 /* C6 */] <98.30141f
            ? (data[8 /* C9 */] <81.27261f ? -0.0057239407f : 0.031695094f)
            : (data[9 /* C10 */] <-9.5f ? 0.0044814427f : 0.17292787f))
          : (data[6 /* C7 */] <10.049412f
            ? (data[5 /* C6 */] <55.99228f ? -0.020146117f : 0.09999487f)
            : (data[7 /* C8 */] <-52.9967f ? -0.0016249851f : -0.09429976f)))
        : (data[3 /* C4 */] <-91.87092f
          ? (data[7 /* C8 */] <-96.8743f
            ? (data[1 /* C2 */] <14.072781f ? 0.10446613f : -0.008155777f)
            : (data[5 /* C6 */] <-18.763565f ? -0.0070025516f : 0.011904503f))
          : (data[6 /* C7 */] <29.686615f
            ? (data[9 /* C10 */] <80.5f ? 8.0387064E-5f : -0.0055229194f)
            : (data[6 /* C7 */] <45.067245f ? 0.006052606f : -3.7159843E-4f))))
      : (data[2 /* C3 */] <-87.5f
        ? (data[3 /* C4 */] <-3.576908f
          ? (data[1 /* C2 */] <-7.9280205f ? 0.20214225f : 0.120238945f)
          : (data[3 /* C4 */] <26.368515f ? -0.120328866f : 0.054797024f))
        : (data[1 /* C2 */] <43.734245f
          ? (data[8 /* C9 */] <-53.055447f
            ? (data[1 /* C2 */] <-63.96907f ? -0.04169566f : 0.0797516f)
            : (data[2 /* C3 */] <91.5f ? -0.029017022f : 0.08197485f))
          : (data[8 /* C9 */] <81.04638f
            ? (data[7 /* C8 */] <-69.586624f ? 0.012655819f : -0.11202993f)
            : 0.08928085f))));
    return pred;
  }
}


class GBM_Model_Forest_49 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBM_Model_Tree_49_class_0.score0(fdata);
  }
}
class GBM_Model_Tree_49_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[9 /* C10 */] != 87.0f
      ? (data[6 /* C7 */] <-82.03046f
        ? (data[1 /* C2 */] <79.68625f
          ? (data[1 /* C2 */] <74.071976f
            ? (data[4 /* C5 */] <53.101746f ? 0.005398486f : -0.007595288f)
            : (data[3 /* C4 */] <-40.599304f ? -0.0049789636f : 0.060669597f))
          : (data[4 /* C5 */] <-49.99535f
            ? (data[7 /* C8 */] <-89.90672f ? -0.20003036f : -0.04010655f)
            : (data[3 /* C4 */] <6.3323975E-4f ? 0.019258218f : -0.023428101f)))
        : (data[3 /* C4 */] <95.31032f
          ? (data[5 /* C6 */] <87.49901f
            ? (data[5 /* C6 */] <84.56937f ? -4.8529764E-4f : -0.011048364f)
            : (data[4 /* C5 */] <-96.873726f ? 0.041975908f : 0.0018822365f))
          : (data[3 /* C4 */] <96.00611f
            ? (data[5 /* C6 */] <-13.871998f ? 0.06250567f : 0.0038218745f)
            : (data[2 /* C3 */] <-59.5f ? 0.02319f : -0.006056275f))))
      : (data[6 /* C7 */] <-8.789368f
        ? (data[1 /* C2 */] <-72.42857f
          ? (data[2 /* C3 */] <-12.0f ? 0.17669453f : -0.015805686f)
          : (data[1 /* C2 */] <62.31347f
            ? (data[2 /* C3 */] <-10.0f ? -0.012837675f : -0.06700414f)
            : (data[6 /* C7 */] <-42.74543f ? 0.11242433f : -0.027147638f)))
        : (data[8 /* C9 */] <68.665665f
          ? (data[4 /* C5 */] <-87.34698f
            ? 0.19457278f
            : (data[5 /* C6 */] <34.314484f ? 0.017715616f : 0.092763245f))
          : (data[1 /* C2 */] <-20.19674f
            ? 0.07347213f
            : (data[1 /* C2 */] <46.991478f ? -0.19633171f : -0.002592311f)))));
    return pred;
  }
}



